using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BusinessWeb.Models.Odoo
{
	public class F_COMPTET
	{
		public bool active { get; set; }
		public int active_lang_count { get; set; }
		public int activity_calendar_event_id { get; set; }
		public DateTime activity_date_deadline { get; set; }
		public string activity_exception_decoration { get; set; }
		public string activity_exception_icon { get; set; }
		public List<int> activity_ids { get; set; }
		public string activity_state { get; set; }
		public string activity_summary { get; set; }
		public string activity_type_icon { get; set; }
		public int activity_type_id { get; set; }
		public int activity_user_id { get; set; }
		public string additional_info { get; set; }
		public byte[] avatar_1024 { get; set; }
		public byte[] avatar_128 { get; set; }
		public byte[] avatar_1920 { get; set; }
		public byte[] avatar_256 { get; set; }
		public byte[] avatar_512 { get; set; }
		public int bank_account_count { get; set; }
		public List<int> bank_ids { get; set; }
		public string barcode { get; set; }
		public DateTime calendar_last_notif_ack { get; set; }
		public bool can_publish { get; set; }
		public List<int> category_id { get; set; }
		public List<int> channel_ids { get; set; }
		public List<int> child_ids { get; set; }
		public string city { get; set; }
		public int color { get; set; }
		public string comment { get; set; }
		public string commercial_company_name { get; set; }
		public int commercial_partner_id { get; set; }
		public int company_id { get; set; }
		public string company_name { get; set; }
		public string company_registry { get; set; }
		public string company_type { get; set; }
		public string complete_name { get; set; }
		public string contact_address { get; set; }
		public string contact_address_inline { get; set; }
		public List<int> contract_ids { get; set; }
		public string country_code { get; set; }
		public int country_id { get; set; }
		public DateTime create_date { get; set; }
		public int create_uid { get; set; }
		public decimal credit { get; set; }
		public float credit_limit { get; set; }
		public decimal credit_to_invoice { get; set; }
		public int currency_id { get; set; }
		public int customer_rank { get; set; }
		public DateTime date { get; set; }
		public DateTime date_localization { get; set; }
		public float days_sales_outstanding { get; set; }
		public decimal debit { get; set; }
		public decimal debit_limit { get; set; }
		public string display_name { get; set; }
		public int duplicated_bank_account_partners_count { get; set; }
		public string email { get; set; }
		public string email_formatted { get; set; }
		public string email_normalized { get; set; }
		public bool employee { get; set; }
		public List<int> employee_ids { get; set; }
		public int employees_count { get; set; }
		public int event_count { get; set; }
		public string fiscal_country_codes { get; set; }
		public string function { get; set; }
		public bool has_message { get; set; }
		public bool has_unreconciled_entries { get; set; }
		public int id { get; set; }
		public string im_status { get; set; }
		public byte[] image_1024 { get; set; }
		public byte[] image_128 { get; set; }
		public byte[] image_1920 { get; set; }
		public byte[] image_256 { get; set; }
		public byte[] image_512 { get; set; }
		public int industry_id { get; set; }
		public List<int> invoice_ids { get; set; }
		public string invoice_warn { get; set; }
		public string invoice_warn_msg { get; set; }
		public bool is_blacklisted { get; set; }
		public bool is_company { get; set; }
		public bool is_public { get; set; }
		public bool is_published { get; set; }
		public bool is_seo_optimized { get; set; }
		public int journal_item_count { get; set; }
		public string lang { get; set; }
		public DateTime last_time_entries_checked { get; set; }
		public int last_website_so_id { get; set; }
		public int meeting_count { get; set; }
		public List<int> meeting_ids { get; set; }
		public int message_attachment_count { get; set; }
		public int message_bounce { get; set; }
		public List<int> message_follower_ids { get; set; }
		public bool message_has_error { get; set; }
		public int message_has_error_counter { get; set; }
		public bool message_has_sms_error { get; set; }
		public List<int> message_ids { get; set; }
		public bool message_is_follower { get; set; }
		public bool message_needaction { get; set; }
		public int message_needaction_counter { get; set; }
		public List<int> message_partner_ids { get; set; }
		public string mobile { get; set; }
		public bool mobile_blacklisted { get; set; }
		public DateTime my_activity_date_deadline { get; set; }
		public string name { get; set; }
		public int parent_id { get; set; }
		public string parent_name { get; set; }
		public int partner_gid { get; set; }
		public float partner_latitude { get; set; }
		public float partner_longitude { get; set; }
		public bool partner_share { get; set; }
		public int payment_token_count { get; set; }
		public List<int> payment_token_ids { get; set; }
		public string peppol_eas { get; set; }
		public string peppol_endpoint { get; set; }
		public string phone { get; set; }
		public bool phone_blacklisted { get; set; }
		public string phone_mobile_search { get; set; }
		public string phone_sanitized { get; set; }
		public bool phone_sanitized_blacklisted { get; set; }
		public string picking_warn { get; set; }
		public string picking_warn_msg { get; set; }
		public int property_account_payable_id { get; set; }
		public int property_account_position_id { get; set; }
		public int property_account_receivable_id { get; set; }
		public int property_delivery_carrier_id { get; set; }
		public int property_payment_term_id { get; set; }
		public int property_product_pricelist { get; set; }
		public int property_stock_customer { get; set; }
		public int property_stock_supplier { get; set; }
		public int property_supplier_payment_term_id { get; set; }
		public List<int> rating_ids { get; set; }
		public List<int> ref_company_ids { get; set; }
		public int sale_order_count { get; set; }
		public List<int> sale_order_ids { get; set; }
		public string sale_warn { get; set; }
		public string sale_warn_msg { get; set; }
		public int same_company_registry_partner_id { get; set; }
		public int same_vat_partner_id { get; set; }
		public string seo_name { get; set; }
		public bool show_credit_limit { get; set; }
		public DateTime signup_expiration { get; set; }
		public string signup_token { get; set; }
		public string signup_type { get; set; }
		public string signup_url { get; set; }
		public bool signup_valid { get; set; }
		public List<int> starred_message_ids { get; set; }
		public int state_id { get; set; }
		public string static_map_url { get; set; }
		public bool static_map_url_is_valid { get; set; }
		public string street { get; set; }
		public string street2 { get; set; }
		public int supplier_rank { get; set; }
		public int team_id { get; set; }
		public int title { get; set; }
		public decimal total_invoiced { get; set; }
		public string trust { get; set; }
		public string type { get; set; }
		public string tz { get; set; }
		public string tz_offset { get; set; }
		public string ubl_cii_format { get; set; }
		public bool use_partner_credit_limit { get; set; }
		public int user_id { get; set; }
		public List<int> user_ids { get; set; }
		public string vat { get; set; }
		public int website_id { get; set; }
		public bool website_is_published { get; set; }
		public string website_meta_description { get; set; }
		public string website_meta_keywords { get; set; }
		public string website_meta_title { get; set; }
		public List<int> website_message_ids { get; set; }
		public string website_published_type { get; set; }
		public string website_short_description { get; set; }
		public string website_url { get; set; }
		public string zip { get; set; }
	}
}

