// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using BusinessWeb.Data;

#nullable disable

namespace BusinessWeb.Migrations
{
    [DbContext(typeof(ApplicationIdentityDbContext))]
    [Migration("00000000000000_Migration_250923_1041")]
    partial class Migration_250923_1041
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {

        }
    }
}
