// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using BusinessWeb.Data;

#nullable disable

namespace BusinessWeb.Migrations
{
    [DbContext(typeof(DB))]
    [Migration("00000000000000_Migration_Init_210923_1003")]
    partial class Migration_Init_210923_1003
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {

        }
    }
}
