// <auto-generated />
using BusinessWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace BusinessWeb.Migrations
{
	[DbContext(typeof(DB))]
	[Migration("00000000000000_Migration_Init9999__260526_ReleveReglements")]
	partial class Migration_Init9999__260526_ReleveReglements
	{
		protected override void BuildTargetModel(ModelBuilder modelBuilder)
		{
		}
	}
}
