// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using BusinessWeb.Data;

#nullable disable

namespace BusinessWeb.Migrations
{
    [DbContext(typeof(DB))]
    [Migration("00000000000000_Migration_Init6_140324_1249")]
    partial class Migration_Init6_140324_1249
	{
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {

        }
    }
}
