// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class API_T_OrdreFabrication
{
    public int id { get; set; }

    public DateTime? Date { get; set; }

    public string Numero { get; set; }

    public string Reference { get; set; }

    public string CA_Num { get; set; }

    public string CT_Num { get; set; }

    public int? Responsable { get; set; }

    public int Statut { get; set; }

    public string NumCommande { get; set; }

    public string NumPreparationCommande { get; set; }

    public bool PreparationCreated { get; set; }

    public DateTime? DateLivraison { get; set; }

    public virtual ICollection<API_T_OrdreFabricationLigne> API_T_OrdreFabricationLigne { get; set; } = new List<API_T_OrdreFabricationLigne>();

    public virtual ICollection<API_T_OrdreFabricationPointage> API_T_OrdreFabricationPointage { get; set; } = new List<API_T_OrdreFabricationPointage>();

    public virtual F_COMPTEA CA_NumNavigation { get; set; }

    public virtual F_COMPTET CT_NumNavigation { get; set; }

    public virtual API_T_Personnel ResponsableNavigation { get; set; }
}