// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class API_T_Taxe
{
    public int id { get; set; }

    public int TA_Sens { get; set; }

    public string CG_Num { get; set; }

    public decimal TA_Taux { get; set; }

    public int Societe { get; set; }

    public string Intitule { get; set; }
}