// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class API_T_RevisionPrix
{
    public int id { get; set; }

    public int Projet { get; set; }

    public virtual API_T_Projet ProjetNavigation { get; set; }
}