// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB
{
    public partial class API_V_PROJET
    {
        public int id { get; set; }
        public string CA_Num { get; set; }
        public string CT_Num { get; set; }
        public string Objet { get; set; }
        public int Site { get; set; }
        public int Ville { get; set; }
        public int TypeMarche { get; set; }
        public int SituationMarche { get; set; }
        public int PhaseMarche { get; set; }
        public DateTime? DateOuverturePils { get; set; }
        public DateTime? DateOrdreNotification { get; set; }
        public DateTime? DateEnregistrement { get; set; }
        public DateTime? DateReceptionDefinitivePrevue { get; set; }
        public DateTime? DateReceptionDefinitiveEffective { get; set; }
        public DateTime? DateOrdreService { get; set; }
        public DateTime? DateExemplaireUnique { get; set; }
        public decimal CoutMarchePrevisionnel { get; set; }
        public decimal TotalMarcheTTC { get; set; }
        public decimal TotalMarcheHT { get; set; }
        public decimal MontantRetenueGarantie { get; set; }
        public decimal TauxRetenueGarantie { get; set; }
        public decimal TauxRetenueGarantieDecompte { get; set; }
        public string NumeroMarche { get; set; }
        public string PeriodeExecutionResume { get; set; }
        public string PeriodeExecutionDetail { get; set; }
        public string ObjetDetail { get; set; }
        public DateTime? DatePublication { get; set; }
        public bool? Resultat { get; set; }
        public int? ModeSoumission { get; set; }
        public int? TypeAppelOffre { get; set; }
        public decimal? MontantAppelOffreEstime { get; set; }
        public bool? IsAppelOffre { get; set; }
        public string Utilisateur { get; set; }
        public string NumeroAppelOffre { get; set; }
        public DateTime? DateEnregistrementCPS { get; set; }
        public DateTime? DateEnregistrementExemplaire { get; set; }
        public string ResultatMarchePV { get; set; }
        public int ResultatMarche { get; set; }
        public string CT_Intitule { get; set; }
        public string CA_Intitule { get; set; }
        public string ZoneIntitule { get; set; }
        public string VilleIntitule { get; set; }
        public string SituationMarcheIntitule { get; set; }
        public string TypeMarcheIntitule { get; set; }
        public string PhaseMarcheIntitule { get; set; }
        public string ModeSoumissionIntitule { get; set; }
        public string TypeAppelOffreIntitule { get; set; }
        public string ResultatMarcheIntitule { get; set; }
    }
}