// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class API_T_Depot_User
{
    public int id { get; set; }

    public int Depot { get; set; }

    public string User { get; set; }
}