// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class API_T_Paiement
{
    public int id { get; set; }

    public DateTime? Date { get; set; }

    public DateTime? RG_Date { get; set; }

    public string RG_Piece { get; set; }

    public string RG_Libelle { get; set; }

    public DateTime? RG_Echeance { get; set; }

    public string RG_Reference { get; set; }

    public string EC_Piece { get; set; }

    public string EC_Intitule { get; set; }

    public string EC_RefPiece { get; set; }

    public string EC_Lettrage { get; set; }

    public decimal? EC_Montant { get; set; }

    public int? EC_No { get; set; }

    public int? cbMarq { get; set; }

    public int? EC_Sens { get; set; }

    public string CG_Num { get; set; }

    public string SrcRappro { get; set; }

    public string MoisRappro { get; set; }

    public string CT_Num { get; set; }

    public DateTime? EC_Date { get; set; }

    public DateTime? JM_Date { get; set; }

    public DateTime? EC_DateRappro { get; set; }

    public int? Mois { get; set; }

    public int? Annee { get; set; }

    public int? ModePaiement { get; set; }

    public string ModePaiementChar { get; set; }

    public int RG_Type { get; set; }

    public int Societe { get; set; }

    public int Declaration { get; set; }

    public string JO_Num { get; set; }

    public string Src { get; set; }

    public string CT_Intitule { get; set; }

    public bool Ignored { get; set; }

    public virtual ICollection<API_T_Facture> API_T_Facture { get; set; } = new List<API_T_Facture>();
}