// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class API_T_PointageJournee
{
    public int id { get; set; }

    public int AnneeID { get; set; }

    public int MoisID { get; set; }

    public DateTime Date { get; set; }

    public bool Cloture { get; set; }

    public DateTime? Creation { get; set; }

    public DateTime? Modification { get; set; }

    public string CreationIP { get; set; }

    public string ModificationIP { get; set; }

    public string CreationHost { get; set; }

    public string ModificationHost { get; set; }

    public string CreationUser { get; set; }

    public string ModificationUser { get; set; }

    public virtual ICollection<API_T_AvancementDetail> API_T_AvancementDetail { get; set; } = new List<API_T_AvancementDetail>();

    public virtual ICollection<API_T_AvancementHorsBD> API_T_AvancementHorsBD { get; set; } = new List<API_T_AvancementHorsBD>();

    public virtual ICollection<API_T_PointageDetail> API_T_PointageDetail { get; set; } = new List<API_T_PointageDetail>();

    public virtual ICollection<API_T_PointageProjet> API_T_PointageProjet { get; set; } = new List<API_T_PointageProjet>();

    public virtual API_T_PointageAnnee Annee { get; set; }

    public virtual API_T_PointageMois Mois { get; set; }
}