// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class API_T_OrdreFabricationPointage
{
    public int id { get; set; }

    public int Ordre { get; set; }

    public int Presonnel { get; set; }

    public DateTime? Date { get; set; }

    public TimeSpan? Debut { get; set; }

    public TimeSpan? Fin { get; set; }

    public decimal FraisJournalier { get; set; }

    public decimal AutresFrais { get; set; }

    public virtual API_T_OrdreFabrication OrdreNavigation { get; set; }

    public virtual API_T_Personnel PresonnelNavigation { get; set; }
}