// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class API_T_CategorieAchat
{
    public int Id { get; set; }

    public string Nom { get; set; }

    public string Description { get; set; }

    public virtual ICollection<API_T_Facture> API_T_Facture { get; set; } = new List<API_T_Facture>();
}