// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class API_T_HistoriqueModification
{
    public int Id { get; set; }

    public string TableAffectee { get; set; }

    public int ID_Affecte { get; set; }

    public int UtilisateurId { get; set; }

    public DateTime? DateModification { get; set; }

    public string AncienneValeur { get; set; }

    public string NouvelleValeur { get; set; }
}