// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class API_T_AgenceContrat
{
    public int id { get; set; }

    public DateTime? Date { get; set; }

    public DateTime? DateDebut { get; set; }

    public DateTime? DateFin { get; set; }

    public int Tiers { get; set; }

    public string CT_Num { get; set; }

    public int Statut { get; set; }

    public int Devise { get; set; }

    public decimal Taux { get; set; }

    public string Piece { get; set; }

    public string Libelle { get; set; }

    public string Fichier { get; set; }

    public int Type { get; set; }

    public string Reference { get; set; }

    public int KidAgeEnd { get; set; }

    public int Regime { get; set; }

    public int InfantStart { get; set; }

    public int InfantEnd { get; set; }

    public int ChildStart { get; set; }

    public int ChildEnd { get; set; }

    public int AdultStart { get; set; }

    public decimal RemiseInfant { get; set; }

    public decimal RemiseChild { get; set; }

    public decimal Tax { get; set; }

    public DateTime? Creation { get; set; }

    public DateTime? Modification { get; set; }

    public string CreationIP { get; set; }

    public string ModificationIP { get; set; }

    public string CreationHost { get; set; }

    public string ModificationHost { get; set; }

    public string CreationUser { get; set; }

    public string ModificationUser { get; set; }

    public virtual ICollection<API_T_AgenceContratDate> API_T_AgenceContratDate { get; set; } = new List<API_T_AgenceContratDate>();

    public virtual ICollection<API_T_AgenceContratLigne> API_T_AgenceContratLigne { get; set; } = new List<API_T_AgenceContratLigne>();

    public virtual ICollection<API_T_AgenceOffre> API_T_AgenceOffre { get; set; } = new List<API_T_AgenceOffre>();

    public virtual F_COMPTET TiersNavigation { get; set; }
}