// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class API_T_CertifPointage
{
    public int id { get; set; }

    public DateTime? Date { get; set; }

    public string CT_Num { get; set; }

    public string Ville { get; set; }

    public DateTime? DateDebutEtalonnage { get; set; }

    public DateTime? DateFinEtalonnage { get; set; }

    public int? ResponsableEtalonnage { get; set; }

    public DateTime? DateReceptionDossier { get; set; }

    public DateTime? DateDebutSaisie { get; set; }

    public DateTime? DateFinSaisie { get; set; }

    public int? NombreCertificats { get; set; }

    public int? ResponsableSaisie { get; set; }

    public int? ResponsableImpression { get; set; }

    public int? VerificationAvantImpression { get; set; }

    public int? VerificationApresImpression { get; set; }

    public bool? Certificats { get; set; }

    public bool? VerificationScan { get; set; }

    public bool? Facture { get; set; }

    public bool? BonDeLivraison { get; set; }

    public string NumeroFACBL { get; set; }

    public DateTime? DateLivraison { get; set; }

    public string Livreur { get; set; }

    public bool? AccuseReception { get; set; }

    public string Commentaire { get; set; }

    public DateTime? DateCreation { get; set; }

    public DateTime? DateModification { get; set; }

    public int? ResponsableEtalonnage2 { get; set; }

    public int? ResponsableEtalonnage3 { get; set; }

    public int? Statut { get; set; }

    public virtual F_COMPTET CT_NumNavigation { get; set; }

    public virtual API_T_Personnel ResponsableEtalonnage2Navigation { get; set; }

    public virtual API_T_Personnel ResponsableEtalonnage3Navigation { get; set; }

    public virtual API_T_Personnel ResponsableEtalonnageNavigation { get; set; }

    public virtual API_T_Personnel ResponsableImpressionNavigation { get; set; }

    public virtual API_T_Personnel ResponsableSaisieNavigation { get; set; }

    public virtual API_T_Personnel VerificationApresImpressionNavigation { get; set; }

    public virtual API_T_Personnel VerificationAvantImpressionNavigation { get; set; }
}