// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class API_V_ORDREFABRICATION
{
    public int id { get; set; }

    public DateTime? Date { get; set; }

    public string Numero { get; set; }

    public string Reference { get; set; }

    public string CA_Num { get; set; }

    public string CT_Num { get; set; }

    public int? Responsable { get; set; }

    public int Statut { get; set; }

    public string NumCommande { get; set; }

    public string NumPreparationCommande { get; set; }

    public bool PreparationCreated { get; set; }

    public DateTime? DateLivraison { get; set; }

    public bool StockCreated { get; set; }

    public string CT_Intitule { get; set; }

    public string CA_Intitule { get; set; }

    public string AR_Refs { get; set; }
}