// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class API_T_AttributeDetail
{
    public int id { get; set; }

    public int ParentID { get; set; }

    public string TextValue { get; set; }

    public DateTime? DateValue { get; set; }

    public bool BoolValue { get; set; }

    public decimal DecimalValue { get; set; }

    public int IntValue { get; set; }

    public int ModelValue { get; set; }

    public int TableValue { get; set; }

    public int ChildID { get; set; }

    public string TableName { get; set; }

    public int TableIndex { get; set; }

    public DateTime? Creation { get; set; }

    public DateTime? Modification { get; set; }

    public string CreationIP { get; set; }

    public string ModificationIP { get; set; }

    public string CreationHost { get; set; }

    public string ModificationHost { get; set; }

    public string CreationUser { get; set; }

    public string ModificationUser { get; set; }

    public virtual ICollection<API_T_AttributeTable> API_T_AttributeTable { get; set; } = new List<API_T_AttributeTable>();

    public virtual API_T_Attribute Parent { get; set; }
}