// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class API_T_AgenceContratDate
{
    public int id { get; set; }

    public int Contrat { get; set; }

    public DateTime? DateDebut { get; set; }

    public DateTime? DateFin { get; set; }

    public virtual ICollection<API_T_AgenceContratDetail> API_T_AgenceContratDetail { get; set; } = new List<API_T_AgenceContratDetail>();

    public virtual API_T_AgenceContrat ContratNavigation { get; set; }
}