// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class API_T_AgenceContratDetail
{
    public int id { get; set; }

    public int Periode { get; set; }

    public int Ligne { get; set; }

    public decimal PU { get; set; }

    public decimal PUDevise { get; set; }

    public decimal Taux { get; set; }

    public string FR_Num { get; set; }

    public string CL_Num { get; set; }

    public int Contrat { get; set; }

    public int Article { get; set; }

    public virtual API_T_AgenceContratLigne LigneNavigation { get; set; }

    public virtual API_T_AgenceContratDate PeriodeNavigation { get; set; }
}