// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class API_T_Assurance
{
    public int id { get; set; }

    public int Type { get; set; }

    public int? Projet { get; set; }

    public int? Materiel { get; set; }

    public int? Personnel { get; set; }

    public string Fournisseur { get; set; }

    public decimal? Montant { get; set; }

    public int? ModePaiement { get; set; }

    public string Libelle { get; set; }

    public DateTime? DateDebut { get; set; }

    public string Fichier { get; set; }

    public DateTime? DateFin { get; set; }

    public decimal? Prolongement { get; set; }

    public DateTime? NouvelleDateFin { get; set; }

    public DateTime? Creation { get; set; }

    public DateTime? Modification { get; set; }

    public string CreationIP { get; set; }

    public string ModificationIP { get; set; }

    public string CreationHost { get; set; }

    public string ModificationHost { get; set; }

    public string CreationUser { get; set; }

    public string ModificationUser { get; set; }
}