// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class API_T_OrdreFabricationDetail
{
    public int id { get; set; }

    public int Ligne { get; set; }

    public string AR_Ref { get; set; }

    public decimal Qte { get; set; }

    public virtual API_T_OrderFabricationLigne LigneNavigation { get; set; }
}