// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB
{
    public partial class API_V_MATERIELENTRETIEN
    {
        public int id { get; set; }
        public int Materiel { get; set; }
        public int Type { get; set; }
        public DateTime? Date { get; set; }
        public string Piece { get; set; }
        public string Libelle { get; set; }
        public int Responsable { get; set; }
        public DateTime? DateDebut { get; set; }
        public DateTime? DateFin { get; set; }
        public decimal Kilometrage { get; set; }
        public decimal Montant { get; set; }
        public string Fournisseur { get; set; }
        public string CT_Num { get; set; }
        public int Projet { get; set; }
        public decimal KilometrageSuivant { get; set; }
        public DateTime? DateSuivante { get; set; }
        public int Conducteur { get; set; }
        public int? Annee { get; set; }
        public DateTime? DatePaiement { get; set; }
        public DateTime? DateValidite { get; set; }
        public string NumeroQuittance { get; set; }
        public string Fichier { get; set; }
        public string CA_Num { get; set; }
        public string NumeroMarche { get; set; }
        public string Objet { get; set; }
        public string Nom { get; set; }
        public string Intitule { get; set; }
        public string Immatricule { get; set; }
        public decimal? Qte { get; set; }
    }
}