// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class API_T_Remarque
{
    public int id { get; set; }

    public int Type { get; set; }

    public DateTime? Date { get; set; }

    public DateTime? DateAlerte { get; set; }

    public string Remarque { get; set; }

    public string Utilisateur { get; set; }

    public int Realisation { get; set; }

    public string Etape { get; set; }

    public string CAPI_T_Num { get; set; }

    public int? Demande { get; set; }

    public DateTime? Creation { get; set; }

    public DateTime? Modification { get; set; }

    public string CreationIP { get; set; }

    public string ModificationIP { get; set; }

    public string CreationHost { get; set; }

    public string ModificationHost { get; set; }

    public string CreationUser { get; set; }

    public string ModificationUser { get; set; }
}