// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class API_V_CREGLEMENT
{
    public int cbMarq { get; set; }

    public int? RG_No { get; set; }

    public DateTime? RG_Date { get; set; }

    public string RG_Piece { get; set; }

    public string RG_Reference { get; set; }

    public string RG_Libelle { get; set; }

    public string CT_Num { get; set; }

    public string CT_Intitule { get; set; }

    public string JO_Num { get; set; }

    public string JO_Intitule { get; set; }

    public string RG_DateEcheance { get; set; }

    public string Echeance { get; set; }

    public string R_Intitule { get; set; }

    public string CT_Type { get; set; }

    public decimal? RG_Montant { get; set; }

    public decimal? Debit { get; set; }

    public decimal? Credit { get; set; }

    public short? RG_Type { get; set; }

    public bool? Encaiss { get; set; }

    public bool? Impaye { get; set; }

    public bool? Incorpore { get; set; }

    public bool? Depose { get; set; }

    public bool? Rappro { get; set; }

    public DateTime? DateDepot { get; set; }

    public DateTime? DatePaie { get; set; }

    public string Remarque { get; set; }

    public string CG_Num { get; set; }

    public string Annee { get; set; }

    public string Mois { get; set; }

    public string MoisAnnee { get; set; }

    public short RG_Cloture { get; set; }

    public string EtatReglement { get; set; }

    public string EtatLettrage { get; set; }

    public DateTime? DateEcheance { get; set; }

    public decimal? M01 { get; set; }

    public decimal? M02 { get; set; }

    public decimal? M03 { get; set; }

    public decimal? M04 { get; set; }

    public decimal? M05 { get; set; }

    public decimal? M06 { get; set; }

    public decimal? M07 { get; set; }

    public decimal? M08 { get; set; }

    public decimal? M09 { get; set; }

    public decimal? M10 { get; set; }

    public decimal? M11 { get; set; }

    public decimal? M12 { get; set; }

    public string PROT_User { get; set; }

    public DateTime? cbCreation { get; set; }

    public DateTime? cbModification { get; set; }
}