// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB
{
    public partial class API_T_Pointage
    {
        public API_T_Pointage()
        {
            API_T_PointageLigne = new HashSet<API_T_PointageLigne>();
        }

        public int id { get; set; }
        public int? Annee { get; set; }
        public int? Mois { get; set; }
        public int? Type { get; set; }
        public bool? Cloture { get; set; }
        public string Libelle { get; set; }

        public virtual ICollection<API_T_PointageLigne> API_T_PointageLigne { get; set; }
    }
}