// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class API_T_AgenceContratLigne
{
    public int id { get; set; }

    public int Entete { get; set; }

    public string Libelle { get; set; }

    public decimal PU { get; set; }

    public bool IsJourneeReserved { get; set; }

    public int Unite { get; set; }

    public string LibelleFA { get; set; }

    public decimal PUDevise { get; set; }

    public decimal Taux { get; set; }

    public int Devise { get; set; }

    public int Article { get; set; }

    public string Reference { get; set; }

    public DateTime? Creation { get; set; }

    public DateTime? Modification { get; set; }

    public string CreationIP { get; set; }

    public string ModificationIP { get; set; }

    public string CreationHost { get; set; }

    public string ModificationHost { get; set; }

    public string CreationUser { get; set; }

    public string ModificationUser { get; set; }

    public virtual ICollection<API_T_AgenceContratDetail> API_T_AgenceContratDetail { get; set; } = new List<API_T_AgenceContratDetail>();

    public virtual API_T_AgenceArticle ArticleNavigation { get; set; }

    public virtual API_T_AgenceContrat EnteteNavigation { get; set; }
}