// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class API_T_FC_Repas
{
    public int id { get; set; }

    public int? Ligne { get; set; }

    public string CT_Num { get; set; }

    public string AR_Ref { get; set; }

    public int? CepMIN { get; set; }

    public int? CepMAX { get; set; }

    public virtual ICollection<API_T_FC_RepasCompose> API_T_FC_RepasCompose { get; set; } = new List<API_T_FC_RepasCompose>();
}