// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class API_T_FichierJoint
{
    public int Id { get; set; }

    public int? FactureId { get; set; }

    public string NomFichier { get; set; }

    public string URL { get; set; }

    public DateTime? DateAjout { get; set; }

    public virtual API_T_Facture Facture { get; set; }
}