// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class API_T_OrdreFabricationDetail
{
    public int id { get; set; }

    public int Ligne { get; set; }

    public string AR_Ref { get; set; }

    public decimal Qte { get; set; }

    public decimal FraisU { get; set; }

    public bool PreparationCreated { get; set; }

    public string NumDA { get; set; }

    public decimal QteStock { get; set; }

    public decimal QtePreparation { get; set; }

    public virtual F_ARTICLE AR_RefNavigation { get; set; }

    public virtual API_T_OrdreFabricationLigne LigneNavigation { get; set; }
}