// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class API_T_FC_RepasCompose
{
    public int id { get; set; }

    public string AR_Ref { get; set; }

    public string Designation { get; set; }

    public decimal? Qte { get; set; }

    public decimal? PU { get; set; }

    public int? Repas { get; set; }

    public int? Type { get; set; }

    public virtual ICollection<API_T_FC_RepasComposeDetail> API_T_FC_RepasComposeDetail { get; set; } = new List<API_T_FC_RepasComposeDetail>();

    public virtual API_T_FC_Repas RepasNavigation { get; set; }
}