// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class API_T_FC_Charges
{
    public int id { get; set; }

    public string CT_Num { get; set; }

    public int? Rubrique { get; set; }

    public int? Affectation { get; set; }

    public decimal? MontantMensuel { get; set; }

    public decimal? Qté { get; set; }

    public decimal? PU { get; set; }
}