// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB
{
    public partial class API_T_Authorize
    {
        public int id { get; set; }
        public string UserID { get; set; }
        public string Url { get; set; }
        public int? SelectedAPP { get; set; }
    }
}