// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class API_V_CERTIFPOINTAGE
{
    public int id { get; set; }

    public DateTime? Date { get; set; }

    public string CT_Num { get; set; }

    public string Ville { get; set; }

    public DateTime? DateDebutEtalonnage { get; set; }

    public DateTime? DateFinEtalonnage { get; set; }

    public int? ResponsableEtalonnage { get; set; }

    public DateTime? DateReceptionDossier { get; set; }

    public DateTime? DateDebutSaisie { get; set; }

    public DateTime? DateFinSaisie { get; set; }

    public int? NombreCertificats { get; set; }

    public int? ResponsableSaisie { get; set; }

    public int? ResponsableImpression { get; set; }

    public int? VerificationAvantImpression { get; set; }

    public int? VerificationApresImpression { get; set; }

    public bool? Certificats { get; set; }

    public bool? VerificationScan { get; set; }

    public bool? Facture { get; set; }

    public bool? BonDeLivraison { get; set; }

    public string NumeroFACBL { get; set; }

    public DateTime? DateLivraison { get; set; }

    public string Livreur { get; set; }

    public bool? AccuseReception { get; set; }

    public string Commentaire { get; set; }

    public DateTime? DateCreation { get; set; }

    public DateTime? DateModification { get; set; }

    public int? ResponsableEtalonnage2 { get; set; }

    public int? ResponsableEtalonnage3 { get; set; }

    public int? Statut { get; set; }

    public string NumeroDE { get; set; }

    public string Intermediaire { get; set; }

    public string CT_Intitule { get; set; }

    public string CT_Adresse { get; set; }

    public string CT_Ville { get; set; }

    public string StatutIntitule { get; set; }

    public string ResponsableEtalonnageIntitule { get; set; }

    public string ResponsableEtalonnage2Intitule { get; set; }

    public string ResponsableEtalonnage3Intitule { get; set; }

    public string ResponsableSaisieIntitule { get; set; }

    public string VerificationAvantImpressionIntitule { get; set; }

    public string VerificationApresImpressionIntitule { get; set; }

    public string CertificatsIntitule { get; set; }

    public string VerificationScanIntitule { get; set; }

    public string FactureIntitule { get; set; }

    public string BonDeLivraisonIntitule { get; set; }

    public string AccuseReceptionIntitule { get; set; }
}