// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class API_T_OrdreFabricationOperation
{
    public int id { get; set; }

    public int Ligne { get; set; }

    public virtual API_T_OrdreFabricationLigne LigneNavigation { get; set; }
}