// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class API_V_CERTIFENTETE
{
    public int id { get; set; }

    public int Type { get; set; }

    public string Piece { get; set; }

    public DateTime? Date { get; set; }

    public string Libelle { get; set; }

    public int Beneficiaire { get; set; }

    public int Materiel { get; set; }

    public int Projet { get; set; }

    public int CO_No { get; set; }

    public string CT_Num { get; set; }

    public string CA_Num { get; set; }

    public decimal Montant { get; set; }

    public string CT_Intitule { get; set; }

    public string CA_Intitule { get; set; }

    public string CO_Nom { get; set; }

    public DateTime? DateLivraison { get; set; }

    public string NumeroRapportMission { get; set; }

    public bool? IsFacture { get; set; }

    public DateTime? FactureDate { get; set; }

    public string FactureNum { get; set; }

    public int? FactureID { get; set; }

    public short? Souche { get; set; }

    public string Statut { get; set; }

    public string S_Intitule { get; set; }
}