// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class API_T_AgenceBookingOffre
{
    public int id { get; set; }

    public int Entete { get; set; }

    public int Offre { get; set; }

    public DateTime? SellingDateStart { get; set; }

    public DateTime? SellingDateEnd { get; set; }

    public DateTime? ArrivalDateStart { get; set; }

    public DateTime? ArrivalDateEnd { get; set; }

    public decimal Remise { get; set; }

    public virtual API_T_AgenceBooking EnteteNavigation { get; set; }
}