// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class API_T_CertifRapportMissionLigne
{
    public int id { get; set; }

    public int Rapport { get; set; }

    public int Instrument { get; set; }

    public string Designation { get; set; }

    public string Constructeur { get; set; }

    public string Identifiant { get; set; }

    public string NumeroCertificat { get; set; }

    public string Emplacement { get; set; }

    public int Ligne { get; set; }

    public virtual API_T_CertifInstrument InstrumentNavigation { get; set; }

    public virtual API_T_CertifRapportMission RapportNavigation { get; set; }
}