// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class API_T_Declaration
{
    public int Id { get; set; }

    public int SocieteId { get; set; }

    public DateTime? Periode { get; set; }

    public DateTime? DateSoumission { get; set; }

    public string Statut { get; set; }

    public decimal? TVACollectee { get; set; }

    public decimal? TVADeductible { get; set; }

    public decimal? TVANette { get; set; }

    public string Observation { get; set; }

    public DateTime? DateDebut { get; set; }

    public DateTime? DateFin { get; set; }

    public string Intitule { get; set; }

    public virtual ICollection<API_T_Facture> API_T_Facture { get; set; } = new List<API_T_Facture>();
}