// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class API_T_CertifSuiviDossier
{
    public DateTime? OrdreMissionDate { get; set; }

    public bool? OrdreMissionDateExist { get; set; }

    public string OrdreMissionRef { get; set; }

    public string OrdreMissionRemarque { get; set; }

    public DateTime? RapportMissionDate { get; set; }

    public bool? RapportMissionDateExist { get; set; }

    public string RapportMissionRef { get; set; }

    public string RapportMissionRemarque { get; set; }

    public DateTime? BordereauEnvoiDate { get; set; }

    public bool? BordereauEnvoiDateExist { get; set; }

    public string BordereauEnvoiRef { get; set; }

    public string BordereauEnvoiRemarque { get; set; }

    public DateTime? FicheReceptionDate { get; set; }

    public bool? FicheReceptionDateExist { get; set; }

    public string FicheReceptionRef { get; set; }

    public string FicheReceptionRemarque { get; set; }

    public DateTime? DechargeMaterielDate { get; set; }

    public bool? DechargeMaterielDateExist { get; set; }

    public string DechargeMaterielRef { get; set; }

    public string DechargeMaterielRemarque { get; set; }

    public DateTime? EnqueteSatisfactionDate { get; set; }

    public bool? EnqueteSatisfactionDateExist { get; set; }

    public string EnqueteSatisfactionRef { get; set; }

    public string EnqueteSatisfactionRemarque { get; set; }

    public DateTime? FeuilleMesureDate { get; set; }

    public bool? FeuilleMesureDateExist { get; set; }

    public string FeuilleMesureRef { get; set; }

    public string FeuilleMesureRemarque { get; set; }

    public DateTime? CertificatEtalonnageDate { get; set; }

    public bool? CertificatEtalonnageDateExist { get; set; }

    public string CertificatEtalonnageRef { get; set; }

    public string CertificatEtalonnageRemarque { get; set; }

    public DateTime? FeuilleCalculIncertitudeDate { get; set; }

    public bool? FeuilleCalculIncertitudeDateExist { get; set; }

    public string FeuilleCalculIncertitudeRef { get; set; }

    public string FeuilleCalculIncertitudeRemarque { get; set; }

    public DateTime? ConstatsVerificationDate { get; set; }

    public bool? ConstatsVerificationDateExist { get; set; }

    public string ConstatsVerificationRef { get; set; }

    public string ConstatsVerificationRemarque { get; set; }

    public DateTime? FicheAnomalieTechniqueDate { get; set; }

    public bool? FicheAnomalieTechniqueDateExist { get; set; }

    public string FicheAnomalieTechniqueRef { get; set; }

    public string FicheAnomalieTechniqueRemarque { get; set; }

    public DateTime? AutresDate { get; set; }

    public bool? AutresDateExist { get; set; }

    public string AutresRef { get; set; }

    public string AutresRemarque { get; set; }

    public int id { get; set; }

    public DateTime? Date { get; set; }

    public string Piece { get; set; }

    public string CT_Num { get; set; }
}