// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB
{
    public partial class API_T_MaterielEntretienDetail
    {
        public int id { get; set; }
        public int Entretien { get; set; }
        public decimal Qte { get; set; }
        public string Unite { get; set; }
        public decimal PU { get; set; }
        public decimal Montant { get; set; }
        public string Libelle { get; set; }

        public virtual API_T_MaterielEntretien EntretienNavigation { get; set; }
    }
}