// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class API_V_MATERIEL
{
    public int id { get; set; }

    public string MarqueVH { get; set; }

    public string TypeVH { get; set; }

    public string Immatricule { get; set; }

    public string ImmatriculeWW { get; set; }

    public string DMC { get; set; }

    public string TypeMoteur { get; set; }

    public string Puissance { get; set; }

    public string Usage { get; set; }

    public int Conducteur { get; set; }

    public decimal ValeurVenale { get; set; }

    public decimal ValeurNeuf { get; set; }

    public decimal ValeurPTA { get; set; }

    public decimal ValeurGlage { get; set; }

    public string RC { get; set; }

    public string DR { get; set; }

    public string INC { get; set; }

    public string VOL { get; set; }

    public string BDG { get; set; }

    public string TIERCE { get; set; }

    public string PTA { get; set; }

    public int Type { get; set; }

    public decimal ValeurAchat { get; set; }

    public DateTime? DateAchat { get; set; }

    public string Fournisseur { get; set; }

    public int TypeAchat { get; set; }

    public string NumeroContrat { get; set; }

    public string Modele { get; set; }

    public string Chassis { get; set; }

    public int Carburant { get; set; }

    public string Intitule { get; set; }

    public int Site { get; set; }

    public decimal? Consommation { get; set; }

    public int? Marque { get; set; }

    public DateTime? CarteGriseDebut { get; set; }

    public DateTime? CarteGriseFin { get; set; }

    public int? CarteGriseType { get; set; }

    public decimal ValeurLocation { get; set; }

    public decimal ValeurLeasing { get; set; }

    public DateTime? DateLocation { get; set; }

    public string CarburantIntitule { get; set; }

    public string TypeAchatIntitule { get; set; }

    public string TypeIntitule { get; set; }

    public string MarqueIntitule { get; set; }

    public string PermisNum { get; set; }

    public DateTime? PermisDateDebut { get; set; }

    public DateTime? PermisDateFin { get; set; }

    public string PermisType { get; set; }

    public string Nom { get; set; }
}