// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class API_T_AgenceBookingDetail
{
    public int id { get; set; }

    public int Article { get; set; }

    public string Libelle { get; set; }

    public string LibelleFA { get; set; }

    public int NbrPax { get; set; }

    public int NbrInfant { get; set; }

    public int NbrAdult { get; set; }

    public int NbrChild { get; set; }

    public int Entete { get; set; }

    public int Devise { get; set; }

    public decimal Taux { get; set; }

    public decimal PU_FR { get; set; }

    public decimal PUDevise_FR { get; set; }

    public decimal PU_CL { get; set; }

    public decimal PUDevise_CL { get; set; }

    public int NbtNuit { get; set; }

    public DateTime? Creation { get; set; }

    public DateTime? Modification { get; set; }

    public string CreationIP { get; set; }

    public string ModificationIP { get; set; }

    public string CreationHost { get; set; }

    public string ModificationHost { get; set; }

    public string CreationUser { get; set; }

    public string ModificationUser { get; set; }

    public virtual API_T_AgenceBooking EnteteNavigation { get; set; }
}