// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class API_V_ATTACHEMENT
{
    public int id { get; set; }

    public int Projet { get; set; }

    public DateTime? Date { get; set; }

    public string Piece { get; set; }

    public string Libelle { get; set; }

    public int Responsable { get; set; }

    public decimal Montant { get; set; }

    public decimal MontantMarche { get; set; }

    public decimal MontantCumul { get; set; }

    public decimal MontantReste { get; set; }

    public decimal TauxRabais { get; set; }

    public DateTime? DateDebut { get; set; }

    public DateTime? DateFin { get; set; }

    public int? Statut { get; set; }

    public string NumeroDecompte { get; set; }

    public DateTime? DateDecompte { get; set; }

    public decimal? MontantTTC { get; set; }

    public string CA_Num { get; set; }

    public string Objet { get; set; }

    public string NumeroAppelOffre { get; set; }

    public string NumeroMarche { get; set; }

    public string SiteIntitule { get; set; }

    public string VilleIntitule { get; set; }
}