// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class API_T_CertifRapportMission
{
    public int id { get; set; }

    public DateTime? Date { get; set; }

    public string Piece { get; set; }

    public string Lieu { get; set; }

    public string CT_Num { get; set; }

    public int CO_No { get; set; }

    public string NumeroDossier { get; set; }

    public DateTime? DateDebutTravaux { get; set; }

    public DateTime? DateFinTravaux { get; set; }

    public virtual ICollection<API_T_CertifRapportMissionLigne> API_T_CertifRapportMissionLigne { get; set; } = new List<API_T_CertifRapportMissionLigne>();
}