// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class API_T_CertifOuvertureDossier
{
    public int id { get; set; }

    public string Numero { get; set; }

    public DateTime? Date { get; set; }

    public int CO_No { get; set; }

    public string Intitule { get; set; }

    public string Interlocuteur { get; set; }

    public string Service { get; set; }

    public string Telephone { get; set; }

    public string Fax { get; set; }

    public string Email { get; set; }

    public string Adresse { get; set; }

    public string Commentaire { get; set; }

    public string NumeroDossier { get; set; }

    public DateTime? DateOuverture { get; set; }

    public int Statut { get; set; }

    public DateTime? Creation { get; set; }

    public DateTime? Modification { get; set; }

    public string CreationIP { get; set; }

    public string ModificationIP { get; set; }

    public string CreationHost { get; set; }

    public string ModificationHost { get; set; }

    public string CreationUser { get; set; }

    public string ModificationUser { get; set; }

    public string CT_Num { get; set; }

    public virtual ICollection<API_T_CertifDocument> API_T_CertifDocument { get; set; } = new List<API_T_CertifDocument>();
}