// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class API_T_Ville
{
    public int id { get; set; }

    public string Intitule { get; set; }

    public string Region { get; set; }
}