// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class API_T_OrdreFabricationLigne
{
    public int id { get; set; }

    public int Ordre { get; set; }

    public string AR_Ref { get; set; }

    public decimal Qte { get; set; }

    public virtual ICollection<API_T_OrdreFabricationDetail> API_T_OrdreFabricationDetail { get; set; } = new List<API_T_OrdreFabricationDetail>();

    public virtual ICollection<API_T_OrdreFabricationOperation> API_T_OrdreFabricationOperation { get; set; } = new List<API_T_OrdreFabricationOperation>();

    public virtual F_ARTICLE AR_RefNavigation { get; set; }

    public virtual API_T_OrdreFabrication OrdreNavigation { get; set; }
}