// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB
{
    public partial class API_T_ProjetReception
    {
        public int id { get; set; }
        public int Projet { get; set; }
        public string Nature { get; set; }
        public DateTime? DateReception { get; set; }
        public int? Type { get; set; }
        public string Fichier { get; set; }

        public virtual API_T_Projet ProjetNavigation { get; set; }
    }
}