// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class API_T_FC_RepasComposeDetail
{
    public int id { get; set; }

    public int? Compose { get; set; }

    public string AR_Ref { get; set; }

    public string Designation { get; set; }

    public decimal? Frequence { get; set; }

    public decimal? Grammage { get; set; }

    public decimal? Qte { get; set; }

    public decimal? PU { get; set; }

    public decimal? Total { get; set; }

    public virtual API_T_FC_RepasCompose ComposeNavigation { get; set; }
}