// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class API_T_AvancementDetail
{
    public int id { get; set; }

    public int Avancement { get; set; }

    public int? Article { get; set; }

    public string AR_Ref { get; set; }

    public decimal? Qte { get; set; }

    public decimal? QteMarche { get; set; }

    public decimal? QteReste { get; set; }

    public string Libelle { get; set; }

    public DateTime? DateExecution { get; set; }

    public decimal? PU { get; set; }

    public decimal? Montant { get; set; }

    public int Ligne { get; set; }

    public decimal? QtePrec { get; set; }

    public decimal? QteCumul { get; set; }

    public string Unite { get; set; }

    public string Consistance { get; set; }

    public decimal? MontantMarche { get; set; }

    public decimal? MontantCumul { get; set; }

    public decimal? MontantReste { get; set; }

    public int Journee { get; set; }

    public int Projet { get; set; }

    public string NumeroPrix { get; set; }

    public virtual API_T_PointageJournee JourneeNavigation { get; set; }

    public virtual API_T_Projet ProjetNavigation { get; set; }
}