// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class API_T_Facture
{
    public int Id { get; set; }

    public int? DeclarationId { get; set; }

    public string Numero { get; set; }

    public DateTime DateFacture { get; set; }

    public string ClientFournisseur { get; set; }

    public string ICE { get; set; }

    public decimal MontantHT { get; set; }

    public decimal MontantTVA { get; set; }

    public decimal? MontantTTC { get; set; }

    public string Nature { get; set; }

    public int? CategorieAchatId { get; set; }

    public string ModeReglement { get; set; }

    public DateTime? DateReglement { get; set; }

    public string SourceFacture { get; set; }

    public int Regl { get; set; }

    public string Src { get; set; }

    public bool Ignored { get; set; }

    public bool IsEXO { get; set; }

    public int cbMarq { get; set; }

    public int EC_Lettre { get; set; }

    public string EC_Lettrage { get; set; }

    public decimal Taxe { get; set; }

    public int Ordre { get; set; }

    public virtual ICollection<API_T_FactureTaux> API_T_FactureTaux { get; set; } = new List<API_T_FactureTaux>();

    public virtual ICollection<API_T_FichierJoint> API_T_FichierJoint { get; set; } = new List<API_T_FichierJoint>();

    public virtual API_T_CategorieAchat CategorieAchat { get; set; }

    public virtual API_T_Declaration Declaration { get; set; }

    public virtual API_T_Paiement ReglNavigation { get; set; }
}