// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class API_T_Tiers
{
    public int id { get; set; }

    public int Societe { get; set; }

    public int CT_Type { get; set; }

    public string CT_Num { get; set; }

    public string ICE { get; set; }

    public string IdF { get; set; }

    public string CT_Intitule { get; set; }

    public string NatureService { get; set; }
}