// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class API_T_Config
{
    public int id { get; set; }

    public bool? BL_Releve { get; set; }

    public bool? BL_BalanceClient { get; set; }

    public bool? BL_BalanceFournisseur { get; set; }

    public bool? BL_Marge { get; set; }

    public bool? FA_Releve { get; set; }

    public bool? FA_BalanceClient { get; set; }

    public bool? FA_BalanceFournisseur { get; set; }

    public bool? FA_Marge { get; set; }
}