// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class API_T_CertifDechargeLigne
{
    public int id { get; set; }

    public int FicheReceptionID { get; set; }

    public string Identification { get; set; }

    public string Accessoires { get; set; }

    public int Instrument { get; set; }
}