// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class API_T_Bordereau
{
    public int id { get; set; }

    public int Projet { get; set; }

    public DateTime? Date { get; set; }

    public string Piece { get; set; }

    public string Libelle { get; set; }

    public int Responsable { get; set; }

    public decimal Montant { get; set; }

    public decimal MontantMarche { get; set; }

    public decimal CoutTotale { get; set; }

    public decimal Marge { get; set; }

    public decimal MargeP { get; set; }

    public decimal Rabais { get; set; }

    public decimal? MontantTTC { get; set; }

    public DateTime? Creation { get; set; }

    public DateTime? Modification { get; set; }

    public string CreationIP { get; set; }

    public string ModificationIP { get; set; }

    public string CreationHost { get; set; }

    public string ModificationHost { get; set; }

    public string CreationUser { get; set; }

    public string ModificationUser { get; set; }

    public virtual ICollection<API_T_BordereauDetail> API_T_BordereauDetail { get; set; } = new List<API_T_BordereauDetail>();

    public virtual API_T_Projet ProjetNavigation { get; set; }
}