// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class API_T_AREdit_Hist
{
    public int id { get; set; }

    public DateTime? DateOP { get; set; }

    public DateTime? OldDate { get; set; }

    public string OldPiece { get; set; }

    public string OldCT_Num { get; set; }

    public string OldAR_Ref { get; set; }

    public string OldDesign { get; set; }

    public decimal? OldQte { get; set; }

    public decimal? OldPU { get; set; }

    public decimal? OldTaxe { get; set; }

    public decimal? OldRem { get; set; }

    public decimal? OldHT { get; set; }

    public decimal? OldTTC { get; set; }

    public DateTime? NewDate { get; set; }

    public string NewPiece { get; set; }

    public string NewCT_Num { get; set; }

    public string NewAR_Ref { get; set; }

    public string NewDesign { get; set; }

    public decimal? NewQte { get; set; }

    public decimal? NewPU { get; set; }

    public decimal? NewTaxe { get; set; }

    public decimal? NewRem { get; set; }

    public decimal? NewHT { get; set; }

    public decimal? NewTTC { get; set; }

    public string OldCT_Intitule { get; set; }

    public string NewCT_Intitule { get; set; }

    public int? OldcbMarq { get; set; }

    public int? NewcbMarq { get; set; }
}