// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class API_T_CertifAutoclaves
{
    public int id { get; set; }

    public DateTime? Creation { get; set; }

    public DateTime? Modification { get; set; }

    public string CreationIP { get; set; }

    public string ModificationIP { get; set; }

    public string CreationHost { get; set; }

    public string ModificationHost { get; set; }

    public string CreationUser { get; set; }

    public string ModificationUser { get; set; }

    public string AR_Ref { get; set; }

    public string Code { get; set; }

    public string Essai { get; set; }

    public int EssaiJuge { get; set; }

    public string TemperatureSterilisation { get; set; }

    public int TemperatureSterilisationJuge { get; set; }

    public string Tolerance { get; set; }

    public int ToleranceJuge { get; set; }

    public string TempsSterilisation { get; set; }

    public int TempsSterilisationJuge { get; set; }

    public string TempsEquilibrage { get; set; }

    public int TempsEquilibrageJuge { get; set; }

    public string Stabilite { get; set; }

    public int StabiliteJuge { get; set; }

    public string Homogeneite { get; set; }

    public int HomogeneiteJuge { get; set; }

    public string Pression { get; set; }

    public int PressionJuge { get; set; }

    public string ValeurSterilisatrice { get; set; }

    public int ValeurSterilisatriceJuge { get; set; }

    public string EntreeSondes { get; set; }

    public int EntreeSondesJuge { get; set; }

    public int Dialogue { get; set; }

    public virtual API_T_CertifGrilleDialogue DialogueNavigation { get; set; }
}