// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class API_T_PointageProjet
{
    public int id { get; set; }

    public int Journee { get; set; }

    public int Projet { get; set; }

    public string CA_Num { get; set; }

    public int Site { get; set; }

    public int Responsable { get; set; }

    public string CT_Num { get; set; }

    public int Type { get; set; }

    public DateTime? Creation { get; set; }

    public DateTime? Modification { get; set; }

    public string CreationIP { get; set; }

    public string ModificationIP { get; set; }

    public string CreationHost { get; set; }

    public string ModificationHost { get; set; }

    public string CreationUser { get; set; }

    public string ModificationUser { get; set; }

    public virtual API_T_PointageJournee JourneeNavigation { get; set; }
}