// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB
{
    public partial class API_T_Audit_F_COMPTEA
    {
        public int id { get; set; }
        public string Operation { get; set; }
        public DateTime? Timestamp { get; set; }
        public string Suser_Name { get; set; }
        public string Host_Name { get; set; }
        public string Sage_Name { get; set; }
        public int? cbMarq { get; set; }
        public short N_Analytique { get; set; }
        public string CA_Num { get; set; }
        public string CA_Intitule { get; set; }
        public short? CA_Type { get; set; }
        public string CA_Classement { get; set; }
        public string CA_Raccourci { get; set; }
        public short? CA_Report { get; set; }
        public short? N_Analyse { get; set; }
        public short? CA_Saut { get; set; }
        public short? CA_Sommeil { get; set; }
        public short? CA_Domaine { get; set; }
        public decimal? CA_Achat { get; set; }
        public decimal? CA_Vente { get; set; }
        public int? CO_No { get; set; }
        public short? CA_Statut { get; set; }
        public short? CA_ModeFacturation { get; set; }
    }
}