// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class API_T_ProjetAvenant
{
    public int id { get; set; }

    public int Projet { get; set; }

    public DateTime? DateAvenant { get; set; }

    public decimal MontantAvenant { get; set; }

    public string Libelle { get; set; }

    public string Fichier { get; set; }

    public DateTime? Creation { get; set; }

    public DateTime? Modification { get; set; }

    public string CreationIP { get; set; }

    public string ModificationIP { get; set; }

    public string CreationHost { get; set; }

    public string ModificationHost { get; set; }

    public string CreationUser { get; set; }

    public string ModificationUser { get; set; }

    public virtual API_T_Projet ProjetNavigation { get; set; }
}