// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class API_T_DocumentEntete
{
    public int id { get; set; }

    public int Domaine { get; set; }

    public int Type { get; set; }

    public DateTime? Date { get; set; }

    public string CAPI_T_Num { get; set; }

    public int Personnel { get; set; }

    public int Materiel { get; set; }

    public int CA_Num { get; set; }

    public int DE_No { get; set; }

    public string JO_Num { get; set; }

    public string CG_Num { get; set; }

    public string Libelle { get; set; }

    public decimal MontantHT { get; set; }

    public decimal MontantTTC { get; set; }

    public int Sense { get; set; }

    public DateTime? Creation { get; set; }

    public DateTime? Modification { get; set; }

    public string CreationIP { get; set; }

    public string ModificationIP { get; set; }

    public string CreationHost { get; set; }

    public string ModificationHost { get; set; }

    public string CreationUser { get; set; }

    public string ModificationUser { get; set; }

    public virtual ICollection<API_T_DocumentLigne> API_T_DocumentLigne { get; set; } = new List<API_T_DocumentLigne>();
}