// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB
{
    public partial class API_V_RELEVE
    {
        public string TypeTiers { get; set; }
        public string Groupe { get; set; }
        public string CT_Num { get; set; }
        public DateTime? DO_Date { get; set; }
        public string DO_Piece { get; set; }
        public short? DO_Type { get; set; }
        public short? DO_Domaine { get; set; }
        public string DO_Ref { get; set; }
        public string DO_Libelle { get; set; }
        public decimal? Debit { get; set; }
        public decimal? Credit { get; set; }
        public decimal? MontantTTC { get; set; }
        public decimal MontantRegle { get; set; }
        public decimal? Reste { get; set; }
        public DateTime? DO_Echeance { get; set; }
        public string TypeIntitule { get; set; }
        public string EtatReglement { get; set; }
        public string EtatLettrage { get; set; }
        public int? Jours { get; set; }
        public int? CO_No { get; set; }
        public int? DE_No { get; set; }
        public string CA_Num { get; set; }
        public string Repre { get; set; }
        public int cbMarq { get; set; }
        public int? RG_No { get; set; }
        public decimal? Solde { get; set; }
        public string CO_Nom { get; set; }
        public string CT_Intitule { get; set; }
        public string CT_Ville { get; set; }
        public string DE_Intitule { get; set; }
        public string CA_Intitule { get; set; }
        public int? CO_No2 { get; set; }
        public string CT_Adresse { get; set; }
        public string CT_Telephone { get; set; }
        public string CT_Telecopie { get; set; }
        public string CT_EMail { get; set; }
        public string R_Intitule { get; set; }
        public short? RT_NbJour { get; set; }
        public decimal? BL { get; set; }
        public decimal? RG_Montant { get; set; }
        public decimal? CT_Encours { get; set; }
        public DateTime? DateEcheance { get; set; }
    }
}