// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class F_ABOLIGNEINFOS
{
    public int AL_No { get; set; }

    public string AC_Code { get; set; }

    public byte[] cbAC_Code { get; set; }

    public string AC_Intitule { get; set; }

    public byte[] cbAC_Intitule { get; set; }

    public short? AC_Type { get; set; }

    public string AC_Valeur { get; set; }

    public short? cbProt { get; set; }

    public int cbMarq { get; set; }

    public string cbCreateur { get; set; }

    public DateTime? cbModification { get; set; }

    public int? cbReplication { get; set; }

    public short? cbFlag { get; set; }

    public DateTime? cbCreation { get; set; }

    public Guid? cbCreationUser { get; set; }

    public virtual F_ABOLIGNE AL_NoNavigation { get; set; }
}