// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class F_ABOENTETEINFOS
{
    public int AB_No { get; set; }

    public string AI_Code { get; set; }

    public byte[] cbAI_Code { get; set; }

    public string AI_Intitule { get; set; }

    public byte[] cbAI_Intitule { get; set; }

    public short? AI_Type { get; set; }

    public string AI_Valeur { get; set; }

    public short? cbProt { get; set; }

    public int cbMarq { get; set; }

    public string cbCreateur { get; set; }

    public DateTime? cbModification { get; set; }

    public int? cbReplication { get; set; }

    public short? cbFlag { get; set; }

    public virtual F_ABOENTETE AB_NoNavigation { get; set; }
}