// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class F_AGENDA
{
    public short? AD_Champ { get; set; }

    public string AD_Evenem { get; set; }

    public short? AG_Domaine { get; set; }

    public string AG_Interes { get; set; }

    public byte[] cbAG_Interes { get; set; }

    public DateTime? AG_Debut { get; set; }

    public DateTime? AG_Fin { get; set; }

    public short? AG_Veille { get; set; }

    public string AG_Comment { get; set; }

    public short? AG_Type { get; set; }

    public short? AG_Confirme { get; set; }

    public string AG_HeureDebut { get; set; }

    public string AG_HeureFin { get; set; }

    public short? AG_Ignorer { get; set; }

    public short? AG_Continue { get; set; }

    public int? DL_No { get; set; }

    public int? cbDL_No { get; set; }

    public int? DE_No { get; set; }

    public int? cbDE_No { get; set; }

    public int? PP_No { get; set; }

    public int? cbPP_No { get; set; }

    public int? AD_No { get; set; }

    public short? cbProt { get; set; }

    public int cbMarq { get; set; }

    public string cbCreateur { get; set; }

    public DateTime? cbModification { get; set; }

    public int? cbReplication { get; set; }

    public short? cbFlag { get; set; }

    public DateTime? cbCreation { get; set; }

    public Guid? cbCreationUser { get; set; }

    public virtual F_DEPOT cbDE_NoNavigation { get; set; }

    public virtual F_DOCLIGNE cbDL_NoNavigation { get; set; }

    public virtual F_PROJETPLANNING cbPP_NoNavigation { get; set; }
}