// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class F_ARTGAMME
{
    public string AR_Ref { get; set; }

    public byte[] cbAR_Ref { get; set; }

    public int? AG_No { get; set; }

    public string EG_Enumere { get; set; }

    public short? AG_Type { get; set; }

    public short? cbProt { get; set; }

    public int cbMarq { get; set; }

    public string cbCreateur { get; set; }

    public DateTime? cbModification { get; set; }

    public int? cbReplication { get; set; }

    public short? cbFlag { get; set; }

    public DateTime? cbCreation { get; set; }

    public Guid? cbCreationUser { get; set; }

    public byte[] cbEG_Enumere { get; set; }

    public virtual F_ARTICLE AR_RefNavigation { get; set; }
}