// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB
{
    public partial class F_ARTCLIENT
    {
        public string AR_Ref { get; set; }
        public byte[] cbAR_Ref { get; set; }
        public short? AC_Categorie { get; set; }
        public decimal? AC_PrixVen { get; set; }
        public decimal? AC_Coef { get; set; }
        public short? AC_PrixTTC { get; set; }
        public short? AC_Arrondi { get; set; }
        public short? AC_QteMont { get; set; }
        public short? EG_Champ { get; set; }
        public decimal? AC_PrixDev { get; set; }
        public short? AC_Devise { get; set; }
        public string CT_Num { get; set; }
        public byte[] cbCT_Num { get; set; }
        public decimal? AC_Remise { get; set; }
        public short? AC_Calcul { get; set; }
        public short? AC_TypeRem { get; set; }
        public string AC_RefClient { get; set; }
        public byte[] cbAC_RefClient { get; set; }
        public decimal? AC_CoefNouv { get; set; }
        public decimal? AC_PrixVenNouv { get; set; }
        public decimal? AC_PrixDevNouv { get; set; }
        public decimal? AC_RemiseNouv { get; set; }
        public DateTime? AC_DateApplication { get; set; }
        public short? cbProt { get; set; }
        public int cbMarq { get; set; }
        public string cbCreateur { get; set; }
        public DateTime? cbModification { get; set; }
        public int? cbReplication { get; set; }
        public short? cbFlag { get; set; }

        public virtual F_ARTICLE AR_RefNavigation { get; set; }
        public virtual F_COMPTET CT_NumNavigation { get; set; }
    }
}