// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class F_ARTCOMPTA
{
    public string AR_Ref { get; set; }

    public byte[] cbAR_Ref { get; set; }

    public short? ACP_Type { get; set; }

    public short? ACP_Champ { get; set; }

    public string ACP_ComptaCPT_CompteG { get; set; }

    public string ACP_ComptaCPT_CompteA { get; set; }

    public string ACP_ComptaCPT_Taxe1 { get; set; }

    public string ACP_ComptaCPT_Taxe2 { get; set; }

    public string ACP_ComptaCPT_Taxe3 { get; set; }

    public DateTime? ACP_ComptaCPT_Date1 { get; set; }

    public DateTime? ACP_ComptaCPT_Date2 { get; set; }

    public DateTime? ACP_ComptaCPT_Date3 { get; set; }

    public string ACP_ComptaCPT_TaxeAnc1 { get; set; }

    public string ACP_ComptaCPT_TaxeAnc2 { get; set; }

    public string ACP_ComptaCPT_TaxeAnc3 { get; set; }

    public short? ACP_TypeFacture { get; set; }

    public short? cbProt { get; set; }

    public int cbMarq { get; set; }

    public string cbCreateur { get; set; }

    public DateTime? cbModification { get; set; }

    public int? cbReplication { get; set; }

    public short? cbFlag { get; set; }

    public virtual F_COMPTEG ACP_ComptaCPT_CompteGNavigation { get; set; }

    public virtual F_TAXE ACP_ComptaCPT_Taxe1Navigation { get; set; }

    public virtual F_TAXE ACP_ComptaCPT_Taxe2Navigation { get; set; }

    public virtual F_TAXE ACP_ComptaCPT_Taxe3Navigation { get; set; }

    public virtual F_TAXE ACP_ComptaCPT_TaxeAnc1Navigation { get; set; }

    public virtual F_TAXE ACP_ComptaCPT_TaxeAnc2Navigation { get; set; }

    public virtual F_TAXE ACP_ComptaCPT_TaxeAnc3Navigation { get; set; }

    public virtual F_ARTICLE AR_RefNavigation { get; set; }
}