// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class F_ARTCOMPO
{
    public string AR_Ref { get; set; }

    public byte[] cbAR_Ref { get; set; }

    public string AT_Operation { get; set; }

    public byte[] cbAT_Operation { get; set; }

    public string RP_Code { get; set; }

    public byte[] cbRP_Code { get; set; }

    public string AT_Temps { get; set; }

    public short? AT_Type { get; set; }

    public string AT_Description { get; set; }

    public short? AT_Ordre { get; set; }

    public int? AG_No1Comp { get; set; }

    public int? AG_No2Comp { get; set; }

    public short? AT_TypeRessource { get; set; }

    public short? AT_Chevauche { get; set; }

    public short? AT_Demarre { get; set; }

    public string AT_OperationChevauche { get; set; }

    public byte[] cbAT_OperationChevauche { get; set; }

    public decimal? AT_ValeurChevauche { get; set; }

    public short? AT_TypeChevauche { get; set; }

    public short? cbProt { get; set; }

    public int cbMarq { get; set; }

    public string cbCreateur { get; set; }

    public DateTime? cbModification { get; set; }

    public int? cbReplication { get; set; }

    public short? cbFlag { get; set; }

    public virtual F_ARTICLE AR_RefNavigation { get; set; }

    public virtual F_RESSOURCEPROD RP_CodeNavigation { get; set; }
}