// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class F_CLAVIER
{
    public short? N_Clavier { get; set; }

    public short? CL_Fonction { get; set; }

    public short? CL_Interesse { get; set; }

    public string AR_Ref { get; set; }

    public byte[] cbAR_Ref { get; set; }

    public int? CO_No { get; set; }

    public int? cbCO_No { get; set; }

    public short? CL_Raccourci { get; set; }

    public short? CL_Flag { get; set; }

    public short? CL_Affiche { get; set; }

    public short? cbProt { get; set; }

    public int cbMarq { get; set; }

    public string cbCreateur { get; set; }

    public DateTime? cbModification { get; set; }

    public int? cbReplication { get; set; }

    public short? cbFlag { get; set; }

    public virtual F_ARTICLE AR_RefNavigation { get; set; }

    public virtual F_COLLABORATEUR cbCO_NoNavigation { get; set; }
}