// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class F_COMPTETRAPPEL
{
    public string CT_Num { get; set; }

    public byte[] cbCT_Num { get; set; }

    public DateTime? CR_Date { get; set; }

    public short? CR_Trait { get; set; }

    public decimal? CR_Impayes { get; set; }

    public decimal? CR_Penal { get; set; }

    public DateTime? CR_Echeance { get; set; }

    public short? N_Reglement { get; set; }

    public short? CR_Comptabilisation { get; set; }

    public decimal? CR_SoldeRelance { get; set; }

    public short? cbProt { get; set; }

    public int cbMarq { get; set; }

    public string cbCreateur { get; set; }

    public DateTime? cbModification { get; set; }

    public int? cbReplication { get; set; }

    public short? cbFlag { get; set; }

    public DateTime? cbCreation { get; set; }

    public Guid? cbCreationUser { get; set; }

    public string CR_RefRappel { get; set; }

    public virtual F_COMPTET CT_NumNavigation { get; set; }
}