// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class F_CONTACTA
{
    public short N_Analytique { get; set; }

    public string CA_Num { get; set; }

    public byte[] cbCA_Num { get; set; }

    public string CA_Nom { get; set; }

    public byte[] cbCA_Nom { get; set; }

    public string CA_Prenom { get; set; }

    public byte[] cbCA_Prenom { get; set; }

    public short? N_Service { get; set; }

    public string CA_Fonction { get; set; }

    public string CA_Telephone { get; set; }

    public string CA_TelPortable { get; set; }

    public string CA_Telecopie { get; set; }

    public string CA_EMail { get; set; }

    public short? CA_Civilite { get; set; }

    public short? N_Contact { get; set; }

    public int? CA_No { get; set; }

    public short? cbProt { get; set; }

    public int cbMarq { get; set; }

    public string cbCreateur { get; set; }

    public DateTime? cbModification { get; set; }

    public int? cbReplication { get; set; }

    public short? cbFlag { get; set; }

    public string CA_Facebook { get; set; }

    public string CA_LinkedIn { get; set; }

    public string CA_Skype { get; set; }

    public DateTime? cbCreation { get; set; }

    public Guid? cbCreationUser { get; set; }

    public virtual F_COMPTEA F_COMPTEA { get; set; }
}