// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class F_COMPTEGBUDGETA
{
    public string CG_Num { get; set; }

    public byte[] cbCG_Num { get; set; }

    public short N_Analytique { get; set; }

    public string CA_Num { get; set; }

    public byte[] cbCA_Num { get; set; }

    public short? CG_BATRepart01 { get; set; }

    public short? CG_BATRepart02 { get; set; }

    public short? CG_BATRepart03 { get; set; }

    public short? CG_BATRepart04 { get; set; }

    public short? CG_BATRepart05 { get; set; }

    public short? CG_BATRepart06 { get; set; }

    public decimal? CG_BAVRepart01 { get; set; }

    public decimal? CG_BAVRepart02 { get; set; }

    public decimal? CG_BAVRepart03 { get; set; }

    public decimal? CG_BAVRepart04 { get; set; }

    public decimal? CG_BAVRepart05 { get; set; }

    public decimal? CG_BAVRepart06 { get; set; }

    public decimal? CG_BAVRepartQ01 { get; set; }

    public decimal? CG_BAVRepartQ02 { get; set; }

    public decimal? CG_BAVRepartQ03 { get; set; }

    public decimal? CG_BAVRepartQ04 { get; set; }

    public decimal? CG_BAVRepartQ05 { get; set; }

    public decimal? CG_BAVRepartQ06 { get; set; }

    public short? cbProt { get; set; }

    public int cbMarq { get; set; }

    public string cbCreateur { get; set; }

    public DateTime? cbModification { get; set; }

    public int? cbReplication { get; set; }

    public short? cbFlag { get; set; }

    public virtual F_COMPTEGBUDGET CG_NumNavigation { get; set; }

    public virtual F_COMPTEA F_COMPTEA { get; set; }
}