// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB
{
    public partial class F_DEPOTCONTACT
    {
        public int DE_No { get; set; }
        public string DC_Nom { get; set; }
        public byte[] cbDC_Nom { get; set; }
        public string DC_Prenom { get; set; }
        public byte[] cbDC_Prenom { get; set; }
        public short? N_Service { get; set; }
        public string DC_Fonction { get; set; }
        public string DC_Telephone { get; set; }
        public string DC_TelPortable { get; set; }
        public string DC_Telecopie { get; set; }
        public string DC_EMail { get; set; }
        public short? DC_Civilite { get; set; }
        public short? N_Contact { get; set; }
        public int? DC_No { get; set; }
        public short? cbProt { get; set; }
        public int cbMarq { get; set; }
        public string cbCreateur { get; set; }
        public DateTime? cbModification { get; set; }
        public int? cbReplication { get; set; }
        public short? cbFlag { get; set; }

        public virtual F_DEPOT DE_NoNavigation { get; set; }
    }
}