// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB
{
    public partial class F_DEPOT
    {
        public F_DEPOT()
        {
            F_ABOENTETE = new HashSet<F_ABOENTETE>();
            F_ABOLIGNE = new HashSet<F_ABOLIGNE>();
            F_AGENDA = new HashSet<F_AGENDA>();
            F_ARTSTOCK = new HashSet<F_ARTSTOCK>();
            F_CAISSE = new HashSet<F_CAISSE>();
            F_COMPTET = new HashSet<F_COMPTET>();
            F_DEPOTCONTACT = new HashSet<F_DEPOTCONTACT>();
            F_DEPOTEMPL = new HashSet<F_DEPOTEMPL>();
            F_DOCENTETE = new HashSet<F_DOCENTETE>();
            F_DOCLIGNE = new HashSet<F_DOCLIGNE>();
            F_GAMSTOCK = new HashSet<F_GAMSTOCK>();
            F_LOTFIFO = new HashSet<F_LOTFIFO>();
            F_LOTSERIE = new HashSet<F_LOTSERIE>();
            F_NOMENCLAT = new HashSet<F_NOMENCLAT>();
            F_PREVISION = new HashSet<F_PREVISION>();
            F_PROJETFABRICATION = new HashSet<F_PROJETFABRICATION>();
            F_PROJETPLANNING = new HashSet<F_PROJETPLANNING>();
            F_RESSOURCEPROD = new HashSet<F_RESSOURCEPROD>();
        }

        public int? DE_No { get; set; }
        public string DE_Intitule { get; set; }
        public byte[] cbDE_Intitule { get; set; }
        public string DE_Adresse { get; set; }
        public string DE_Complement { get; set; }
        public string DE_CodePostal { get; set; }
        public string DE_Ville { get; set; }
        public string DE_Contact { get; set; }
        public short? DE_Principal { get; set; }
        public short? DE_CatCompta { get; set; }
        public string DE_Region { get; set; }
        public string DE_Pays { get; set; }
        public string DE_EMail { get; set; }
        public string DE_Code { get; set; }
        public byte[] cbDE_Code { get; set; }
        public string DE_Telephone { get; set; }
        public string DE_Telecopie { get; set; }
        public int? DE_Replication { get; set; }
        public int? DP_NoDefaut { get; set; }
        public int? cbDP_NoDefaut { get; set; }
        public short? DE_Exclure { get; set; }
        public short? cbProt { get; set; }
        public int cbMarq { get; set; }
        public string cbCreateur { get; set; }
        public DateTime? cbModification { get; set; }
        public int? cbReplication { get; set; }
        public short? cbFlag { get; set; }

        public virtual F_DEPOTEMPL cbDP_NoDefautNavigation { get; set; }
        public virtual ICollection<F_ABOENTETE> F_ABOENTETE { get; set; }
        public virtual ICollection<F_ABOLIGNE> F_ABOLIGNE { get; set; }
        public virtual ICollection<F_AGENDA> F_AGENDA { get; set; }
        public virtual ICollection<F_ARTSTOCK> F_ARTSTOCK { get; set; }
        public virtual ICollection<F_CAISSE> F_CAISSE { get; set; }
        public virtual ICollection<F_COMPTET> F_COMPTET { get; set; }
        public virtual ICollection<F_DEPOTCONTACT> F_DEPOTCONTACT { get; set; }
        public virtual ICollection<F_DEPOTEMPL> F_DEPOTEMPL { get; set; }
        public virtual ICollection<F_DOCENTETE> F_DOCENTETE { get; set; }
        public virtual ICollection<F_DOCLIGNE> F_DOCLIGNE { get; set; }
        public virtual ICollection<F_GAMSTOCK> F_GAMSTOCK { get; set; }
        public virtual ICollection<F_LOTFIFO> F_LOTFIFO { get; set; }
        public virtual ICollection<F_LOTSERIE> F_LOTSERIE { get; set; }
        public virtual ICollection<F_NOMENCLAT> F_NOMENCLAT { get; set; }
        public virtual ICollection<F_PREVISION> F_PREVISION { get; set; }
        public virtual ICollection<F_PROJETFABRICATION> F_PROJETFABRICATION { get; set; }
        public virtual ICollection<F_PROJETPLANNING> F_PROJETPLANNING { get; set; }
        public virtual ICollection<F_RESSOURCEPROD> F_RESSOURCEPROD { get; set; }
    }
}