// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB
{
    public partial class F_DOCLIGNEINFOS
    {
        public int DL_No { get; set; }
        public string DC_Code { get; set; }
        public byte[] cbDC_Code { get; set; }
        public string DC_Intitule { get; set; }
        public byte[] cbDC_Intitule { get; set; }
        public short? DC_Type { get; set; }
        public string DC_Valeur { get; set; }
        public short? cbProt { get; set; }
        public int cbMarq { get; set; }
        public string cbCreateur { get; set; }
        public DateTime? cbModification { get; set; }
        public int? cbReplication { get; set; }
        public short? cbFlag { get; set; }

        public virtual F_DOCLIGNE DL_NoNavigation { get; set; }
    }
}