// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class F_DOCENTETEINFOS
{
    public short? DO_Type { get; set; }

    public string DO_Piece { get; set; }

    public byte[] cbDO_Piece { get; set; }

    public string DI_Code { get; set; }

    public byte[] cbDI_Code { get; set; }

    public string DI_Intitule { get; set; }

    public byte[] cbDI_Intitule { get; set; }

    public short? DI_Type { get; set; }

    public string DI_Valeur { get; set; }

    public short? cbProt { get; set; }

    public int cbMarq { get; set; }

    public string cbCreateur { get; set; }

    public DateTime? cbModification { get; set; }

    public int? cbReplication { get; set; }

    public short? cbFlag { get; set; }
}