// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class F_DRECOUVREMENTEC
{
    public string DR_Num { get; set; }

    public byte[] cbDR_Num { get; set; }

    public int EC_No { get; set; }

    public DateTime? EC_DateTiersDouteux { get; set; }

    public short? cbProt { get; set; }

    public int cbMarq { get; set; }

    public string cbCreateur { get; set; }

    public DateTime? cbModification { get; set; }

    public int? cbReplication { get; set; }

    public short? cbFlag { get; set; }

    public virtual F_DRECOUVREMENT DR_NumNavigation { get; set; }

    public virtual F_ECRITUREC EC_NoNavigation { get; set; }
}