// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB
{
    public partial class F_DRECOUVREMENTIV
    {
        public string DR_Num { get; set; }
        public byte[] cbDR_Num { get; set; }
        public short? IV_Statut { get; set; }
        public DateTime? IV_Date { get; set; }
        public string IV_Heure { get; set; }
        public int? ES_No { get; set; }
        public int? cbES_No { get; set; }
        public string IV_User { get; set; }
        public short? IV_NoContactType { get; set; }
        public int? IV_NoContact { get; set; }
        public string IV_Raison { get; set; }
        public short? IV_EnvoiType { get; set; }
        public string IV_Modele { get; set; }
        public string IV_Document { get; set; }
        public short? IV_CalculPenalite { get; set; }
        public decimal? IV_Penalite { get; set; }
        public decimal? IV_FraiImpaye { get; set; }
        public short? IV_Comptabilisation { get; set; }
        public short? IV_Type { get; set; }
        public DateTime? IV_DatePromesse { get; set; }
        public DateTime? IV_DateAlerte { get; set; }
        public short? N_Risque { get; set; }
        public decimal? IV_PerteProbable { get; set; }
        public short? IV_DRStatut { get; set; }
        public short? cbProt { get; set; }
        public int cbMarq { get; set; }
        public string cbCreateur { get; set; }
        public DateTime? cbModification { get; set; }
        public int? cbReplication { get; set; }
        public short? cbFlag { get; set; }

        public virtual F_DRECOUVREMENT DR_NumNavigation { get; set; }
        public virtual F_ESCENARIO cbES_NoNavigation { get; set; }
    }
}