// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class F_DRECOUVREMENT
{
    public string DR_Num { get; set; }

    public byte[] cbDR_Num { get; set; }

    public string CT_Num { get; set; }

    public byte[] cbCT_Num { get; set; }

    public decimal? DR_PerteProbable { get; set; }

    public short? DR_Statut { get; set; }

    public short? DR_Priorite { get; set; }

    public DateTime? DR_DateDebut { get; set; }

    public short? N_Litige { get; set; }

    public string DR_Resume { get; set; }

    public int? CO_No { get; set; }

    public int? cbCO_No { get; set; }

    public int? CT_No { get; set; }

    public int? cbCT_No { get; set; }

    public string DR_Commentaire { get; set; }

    public DateTime? DR_DateFin { get; set; }

    public short? N_Resolution { get; set; }

    public short? DR_Resultat { get; set; }

    public decimal? DR_Provision { get; set; }

    public short? cbProt { get; set; }

    public int cbMarq { get; set; }

    public string cbCreateur { get; set; }

    public DateTime? cbModification { get; set; }

    public int? cbReplication { get; set; }

    public short? cbFlag { get; set; }

    public virtual F_COMPTET CT_NumNavigation { get; set; }

    public virtual ICollection<F_CONTACTR> F_CONTACTR { get; set; } = new List<F_CONTACTR>();

    public virtual ICollection<F_DRECOUVREMENTEC> F_DRECOUVREMENTEC { get; set; } = new List<F_DRECOUVREMENTEC>();

    public virtual ICollection<F_DRECOUVREMENTIV> F_DRECOUVREMENTIV { get; set; } = new List<F_DRECOUVREMENTIV>();

    public virtual F_COLLABORATEUR cbCO_NoNavigation { get; set; }

    public virtual F_CONTACTT cbCT_NoNavigation { get; set; }
}