// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class F_ECRITUREA
{
    public int EC_No { get; set; }

    public short N_Analytique { get; set; }

    public short? EA_Ligne { get; set; }

    public string CA_Num { get; set; }

    public byte[] cbCA_Num { get; set; }

    public decimal? EA_Montant { get; set; }

    public decimal? EA_Quantite { get; set; }

    public short? cbProt { get; set; }

    public int cbMarq { get; set; }

    public string cbCreateur { get; set; }

    public DateTime? cbModification { get; set; }

    public int? cbReplication { get; set; }

    public short? cbFlag { get; set; }

    public DateTime? cbCreation { get; set; }

    public Guid? cbCreationUser { get; set; }

    public virtual F_ECRITUREC EC_NoNavigation { get; set; }

    public virtual F_COMPTEA F_COMPTEA { get; set; }
}