// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class F_ECRITURECMEDIA
{
    public int EC_No { get; set; }

    public string EM_Fichier { get; set; }

    public string EM_Commentaire { get; set; }

    public string EM_TypeMIME { get; set; }

    public string EM_Origine { get; set; }

    public short? cbProt { get; set; }

    public int cbMarq { get; set; }

    public string cbCreateur { get; set; }

    public DateTime? cbModification { get; set; }

    public int? cbReplication { get; set; }

    public short? cbFlag { get; set; }

    public DateTime? cbCreation { get; set; }

    public Guid? cbCreationUser { get; set; }

    public virtual F_ECRITUREC EC_NoNavigation { get; set; }
}