// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class F_ECRITURER
{
    public DateTime? ER_Date { get; set; }

    public string CG_Num { get; set; }

    public byte[] cbCG_Num { get; set; }

    public short N_Analytique { get; set; }

    public string CA_Num { get; set; }

    public byte[] cbCA_Num { get; set; }

    public short? ER_Sens { get; set; }

    public decimal? ER_MontantA { get; set; }

    public decimal? ER_QuantiteA { get; set; }

    public short? ER_Type { get; set; }

    public string JA_Num { get; set; }

    public byte[] cbJA_Num { get; set; }

    public string ER_Piece { get; set; }

    public byte[] cbER_Piece { get; set; }

    public string ER_RefPiece { get; set; }

    public string ER_Intitule { get; set; }

    public int? ER_No { get; set; }

    public short? ER_Norme { get; set; }

    public short? cbProt { get; set; }

    public int cbMarq { get; set; }

    public string cbCreateur { get; set; }

    public DateTime? cbModification { get; set; }

    public int? cbReplication { get; set; }

    public short? cbFlag { get; set; }

    public DateTime? cbCreation { get; set; }

    public Guid? cbCreationUser { get; set; }

    public virtual F_COMPTEG CG_NumNavigation { get; set; }

    public virtual F_COMPTEA F_COMPTEA { get; set; }
}