// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class F_EPROTECTIONCIAL
{
    public int PROT_No { get; set; }

    public int? EPROT_Cmd { get; set; }

    public short? EPROT_Right { get; set; }

    public short? cbProt { get; set; }

    public int cbMarq { get; set; }

    public string cbCreateur { get; set; }

    public DateTime? cbModification { get; set; }

    public int? cbReplication { get; set; }

    public short? cbFlag { get; set; }

    public DateTime? cbCreation { get; set; }

    public Guid? cbCreationUser { get; set; }

    public virtual F_PROTECTIONCIAL PROT_NoNavigation { get; set; }
}