// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class F_ETAXE
{
    public int TA_No { get; set; }

    public string CG_Num { get; set; }

    public byte[] cbCG_Num { get; set; }

    public short? cbProt { get; set; }

    public int cbMarq { get; set; }

    public string cbCreateur { get; set; }

    public DateTime? cbModification { get; set; }

    public int? cbReplication { get; set; }

    public short? cbFlag { get; set; }

    public virtual F_COMPTEG CG_NumNavigation { get; set; }

    public virtual F_TAXE TA_NoNavigation { get; set; }
}