// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class F_ETABLEAU
{
    public string CY_Num { get; set; }

    public byte[] cbCY_Num { get; set; }

    public string TB_Num { get; set; }

    public byte[] cbTB_Num { get; set; }

    public short? ET_Exercice { get; set; }

    public short? ET_Ligne { get; set; }

    public decimal? ET_Colonne01ET_Montant { get; set; }

    public string ET_Colonne01ET_Texte { get; set; }

    public DateTime? ET_Colonne01ET_Date { get; set; }

    public decimal? ET_Colonne02ET_Montant { get; set; }

    public string ET_Colonne02ET_Texte { get; set; }

    public DateTime? ET_Colonne02ET_Date { get; set; }

    public decimal? ET_Colonne03ET_Montant { get; set; }

    public string ET_Colonne03ET_Texte { get; set; }

    public DateTime? ET_Colonne03ET_Date { get; set; }

    public decimal? ET_Colonne04ET_Montant { get; set; }

    public string ET_Colonne04ET_Texte { get; set; }

    public DateTime? ET_Colonne04ET_Date { get; set; }

    public decimal? ET_Colonne05ET_Montant { get; set; }

    public string ET_Colonne05ET_Texte { get; set; }

    public DateTime? ET_Colonne05ET_Date { get; set; }

    public decimal? ET_Colonne06ET_Montant { get; set; }

    public string ET_Colonne06ET_Texte { get; set; }

    public DateTime? ET_Colonne06ET_Date { get; set; }

    public decimal? ET_Colonne07ET_Montant { get; set; }

    public string ET_Colonne07ET_Texte { get; set; }

    public DateTime? ET_Colonne07ET_Date { get; set; }

    public decimal? ET_Colonne08ET_Montant { get; set; }

    public string ET_Colonne08ET_Texte { get; set; }

    public DateTime? ET_Colonne08ET_Date { get; set; }

    public decimal? ET_Colonne09ET_Montant { get; set; }

    public string ET_Colonne09ET_Texte { get; set; }

    public DateTime? ET_Colonne09ET_Date { get; set; }

    public decimal? ET_Colonne10ET_Montant { get; set; }

    public string ET_Colonne10ET_Texte { get; set; }

    public DateTime? ET_Colonne10ET_Date { get; set; }

    public decimal? ET_Colonne11ET_Montant { get; set; }

    public string ET_Colonne11ET_Texte { get; set; }

    public DateTime? ET_Colonne11ET_Date { get; set; }

    public decimal? ET_Colonne12ET_Montant { get; set; }

    public string ET_Colonne12ET_Texte { get; set; }

    public DateTime? ET_Colonne12ET_Date { get; set; }

    public decimal? ET_Colonne13ET_Montant { get; set; }

    public string ET_Colonne13ET_Texte { get; set; }

    public DateTime? ET_Colonne13ET_Date { get; set; }

    public decimal? ET_Colonne14ET_Montant { get; set; }

    public string ET_Colonne14ET_Texte { get; set; }

    public DateTime? ET_Colonne14ET_Date { get; set; }

    public decimal? ET_Colonne15ET_Montant { get; set; }

    public string ET_Colonne15ET_Texte { get; set; }

    public DateTime? ET_Colonne15ET_Date { get; set; }

    public decimal? ET_Colonne16ET_Montant { get; set; }

    public string ET_Colonne16ET_Texte { get; set; }

    public DateTime? ET_Colonne16ET_Date { get; set; }

    public decimal? ET_Colonne17ET_Montant { get; set; }

    public string ET_Colonne17ET_Texte { get; set; }

    public DateTime? ET_Colonne17ET_Date { get; set; }

    public decimal? ET_Colonne18ET_Montant { get; set; }

    public string ET_Colonne18ET_Texte { get; set; }

    public DateTime? ET_Colonne18ET_Date { get; set; }

    public decimal? ET_Colonne19ET_Montant { get; set; }

    public string ET_Colonne19ET_Texte { get; set; }

    public DateTime? ET_Colonne19ET_Date { get; set; }

    public decimal? ET_Colonne20ET_Montant { get; set; }

    public string ET_Colonne20ET_Texte { get; set; }

    public DateTime? ET_Colonne20ET_Date { get; set; }

    public short? cbProt { get; set; }

    public int cbMarq { get; set; }

    public string cbCreateur { get; set; }

    public DateTime? cbModification { get; set; }

    public int? cbReplication { get; set; }

    public short? cbFlag { get; set; }

    public DateTime? cbCreation { get; set; }

    public Guid? cbCreationUser { get; set; }
}