// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB
{
    public partial class F_FAMILLE
    {
        public string FA_CodeFamille { get; set; }
        public byte[] cbFA_CodeFamille { get; set; }
        public short? FA_Type { get; set; }
        public string FA_Intitule { get; set; }
        public byte[] cbFA_Intitule { get; set; }
        public short? FA_UniteVen { get; set; }
        public decimal? FA_Coef { get; set; }
        public short? FA_SuiviStock { get; set; }
        public short? FA_Garantie { get; set; }
        public string FA_Central { get; set; }
        public byte[] cbFA_Central { get; set; }
        public string FA_Stat01 { get; set; }
        public string FA_Stat02 { get; set; }
        public string FA_Stat03 { get; set; }
        public string FA_Stat04 { get; set; }
        public string FA_Stat05 { get; set; }
        public string FA_CodeFiscal { get; set; }
        public string FA_Pays { get; set; }
        public short? FA_UnitePoids { get; set; }
        public short? FA_Escompte { get; set; }
        public short? FA_Delai { get; set; }
        public short? FA_HorsStat { get; set; }
        public short? FA_VteDebit { get; set; }
        public short? FA_NotImp { get; set; }
        public string FA_Frais01FR_Denomination { get; set; }
        public decimal? FA_Frais01FR_Rem01REM_Valeur { get; set; }
        public short? FA_Frais01FR_Rem01REM_Type { get; set; }
        public decimal? FA_Frais01FR_Rem02REM_Valeur { get; set; }
        public short? FA_Frais01FR_Rem02REM_Type { get; set; }
        public decimal? FA_Frais01FR_Rem03REM_Valeur { get; set; }
        public short? FA_Frais01FR_Rem03REM_Type { get; set; }
        public string FA_Frais02FR_Denomination { get; set; }
        public decimal? FA_Frais02FR_Rem01REM_Valeur { get; set; }
        public short? FA_Frais02FR_Rem01REM_Type { get; set; }
        public decimal? FA_Frais02FR_Rem02REM_Valeur { get; set; }
        public short? FA_Frais02FR_Rem02REM_Type { get; set; }
        public decimal? FA_Frais02FR_Rem03REM_Valeur { get; set; }
        public short? FA_Frais02FR_Rem03REM_Type { get; set; }
        public string FA_Frais03FR_Denomination { get; set; }
        public decimal? FA_Frais03FR_Rem01REM_Valeur { get; set; }
        public short? FA_Frais03FR_Rem01REM_Type { get; set; }
        public decimal? FA_Frais03FR_Rem02REM_Valeur { get; set; }
        public short? FA_Frais03FR_Rem02REM_Type { get; set; }
        public decimal? FA_Frais03FR_Rem03REM_Valeur { get; set; }
        public short? FA_Frais03FR_Rem03REM_Type { get; set; }
        public short? FA_Contremarque { get; set; }
        public short? FA_FactPoids { get; set; }
        public short? FA_FactForfait { get; set; }
        public short? FA_Publie { get; set; }
        public string FA_RacineRef { get; set; }
        public string FA_RacineCB { get; set; }
        public int? CL_No1 { get; set; }
        public int? cbCL_No1 { get; set; }
        public int? CL_No2 { get; set; }
        public int? cbCL_No2 { get; set; }
        public int? CL_No3 { get; set; }
        public int? cbCL_No3 { get; set; }
        public int? CL_No4 { get; set; }
        public int? cbCL_No4 { get; set; }
        public short? FA_Nature { get; set; }
        public short? FA_NbColis { get; set; }
        public short? FA_SousTraitance { get; set; }
        public short? FA_Fictif { get; set; }
        public short? cbProt { get; set; }
        public int cbMarq { get; set; }
        public string cbCreateur { get; set; }
        public DateTime? cbModification { get; set; }
        public int? cbReplication { get; set; }
        public short? cbFlag { get; set; }

        public virtual F_CATALOGUE cbCL_No1Navigation { get; set; }
        public virtual F_CATALOGUE cbCL_No2Navigation { get; set; }
        public virtual F_CATALOGUE cbCL_No3Navigation { get; set; }
        public virtual F_CATALOGUE cbCL_No4Navigation { get; set; }
    }
}