// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class F_LIGNEARCHIVE
{
    public string TA_Piece { get; set; }

    public byte[] cbTA_Piece { get; set; }

    public string AR_Ref { get; set; }

    public byte[] cbAR_Ref { get; set; }

    public string LA_Design { get; set; }

    public decimal? LA_PrixUnitaire { get; set; }

    public decimal? LA_PUTTC { get; set; }

    public short? LA_TTC { get; set; }

    public decimal? LA_Qte { get; set; }

    public decimal? LA_Remise01REM_Valeur { get; set; }

    public short? LA_Remise01REM_Type { get; set; }

    public decimal? LA_Remise02REM_Valeur { get; set; }

    public short? LA_Remise02REM_Type { get; set; }

    public decimal? LA_Remise03REM_Valeur { get; set; }

    public short? LA_Remise03REM_Type { get; set; }

    public int? LA_Ligne { get; set; }

    public decimal? LA_Taxe1 { get; set; }

    public short? LA_TypeTaux1 { get; set; }

    public short? LA_TypeTaxe1 { get; set; }

    public decimal? LA_Taxe2 { get; set; }

    public short? LA_TypeTaux2 { get; set; }

    public short? LA_TypeTaxe2 { get; set; }

    public decimal? LA_Taxe3 { get; set; }

    public short? LA_TypeTaux3 { get; set; }

    public short? LA_TypeTaxe3 { get; set; }

    public int? AG_No1 { get; set; }

    public int? AG_No2 { get; set; }

    public string LS_NoSerie { get; set; }

    public int? CO_No { get; set; }

    public int? cbCO_No { get; set; }

    public decimal? LA_PoidsNet { get; set; }

    public short? LA_TRemExep { get; set; }

    public decimal? LA_PrixRU { get; set; }

    public decimal? LA_CMUP { get; set; }

    public string EU_Enumere { get; set; }

    public decimal? EU_Qte { get; set; }

    public short? LA_FactPoids { get; set; }

    public short? LA_Escompte { get; set; }

    public short? LA_Valorise { get; set; }

    public string LS_Complement { get; set; }

    public short? cbProt { get; set; }

    public int cbMarq { get; set; }

    public string cbCreateur { get; set; }

    public DateTime? cbModification { get; set; }

    public int? cbReplication { get; set; }

    public short? cbFlag { get; set; }

    public DateTime? cbCreation { get; set; }

    public Guid? cbCreationUser { get; set; }

    public virtual F_ARTICLE AR_RefNavigation { get; set; }

    public virtual F_TICKETARCHIVE TA_PieceNavigation { get; set; }
}