// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class F_MODELER
{
    public int MR_No { get; set; }

    public string MR_Intitule { get; set; }

    public byte[] cbMR_Intitule { get; set; }

    public short? cbProt { get; set; }

    public int cbMarq { get; set; }

    public string cbCreateur { get; set; }

    public DateTime? cbModification { get; set; }

    public int? cbReplication { get; set; }

    public short? cbFlag { get; set; }

    public virtual ICollection<F_COMPTET> F_COMPTET { get; set; } = new List<F_COMPTET>();

    public virtual ICollection<F_EMODELER> F_EMODELER { get; set; } = new List<F_EMODELER>();
}