// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class F_PROTECTIONCIAL
{
    public string PROT_User { get; set; }

    public byte[] cbCIPROT_User { get; set; }

    public string PROT_Description { get; set; }

    public short? PROT_Right { get; set; }

    public int? PROT_No { get; set; }

    public string PROT_EMail { get; set; }

    public int? PROT_UserProfil { get; set; }

    public int? cbPROT_UserProfil { get; set; }

    public short? PROT_Administrator { get; set; }

    public DateTime? PROT_DatePwd { get; set; }

    public DateTime? PROT_LastLoginDate { get; set; }

    public string PROT_LastLoginTime { get; set; }

    public short? PROT_PwdStatus { get; set; }

    public short? PROT_Disabled { get; set; }

    public int? PROT_ApplicationRight { get; set; }

    public short? PROT_AllowExternalAccess { get; set; }

    public Guid? PROT_Guid { get; set; }

    public byte[] PROT_Hash { get; set; }

    public string PROT_ProviderType { get; set; }

    public Guid? PROT_ProviderID_AAD { get; set; }

    public byte[] PROT_ProviderID_AD { get; set; }

    public short? PROT_ServiceOffice365Actif { get; set; }

    public Guid? PROT_ServiceOffice365UserId { get; set; }

    public short? PROT_ServiceSageIDActif { get; set; }

    public string PROT_ServiceSageIDUserId { get; set; }

    public short? cbProt { get; set; }

    public int cbMarq { get; set; }

    public string cbCreateur { get; set; }

    public DateTime? cbModification { get; set; }

    public int? cbReplication { get; set; }

    public short? cbFlag { get; set; }

    public DateTime? cbCreation { get; set; }

    public Guid? cbCreationUser { get; set; }

    public virtual ICollection<F_EPROTECTIONCIAL> F_EPROTECTIONCIAL { get; set; } = new List<F_EPROTECTIONCIAL>();

    public virtual ICollection<F_PROTECTIONCIAL> InversecbPROT_UserProfilNavigation { get; set; } = new List<F_PROTECTIONCIAL>();

    public virtual F_PROTECTIONCIAL cbPROT_UserProfilNavigation { get; set; }
}