// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class F_PROJETFABRICATION
{
    public string PF_Num { get; set; }

    public byte[] cbPF_Num { get; set; }

    public short? PF_Statut { get; set; }

    public string PF_Intitule { get; set; }

    public byte[] cbPF_Intitule { get; set; }

    public int? DE_No { get; set; }

    public int? cbDE_No { get; set; }

    public string CA_Num { get; set; }

    public byte[] cbCA_Num { get; set; }

    public DateTime? PF_DateDebut { get; set; }

    public DateTime? PF_DateFin { get; set; }

    public string DO_Piece { get; set; }

    public byte[] cbDO_Piece { get; set; }

    public short? PF_Type { get; set; }

    public string CT_Num { get; set; }

    public byte[] cbCT_Num { get; set; }

    public short? cbProt { get; set; }

    public int cbMarq { get; set; }

    public string cbCreateur { get; set; }

    public DateTime? cbModification { get; set; }

    public int? cbReplication { get; set; }

    public short? cbFlag { get; set; }

    public virtual ICollection<F_PROJETHISTO> F_PROJETHISTO { get; set; } = new List<F_PROJETHISTO>();

    public virtual ICollection<F_PROJETLIGNE> F_PROJETLIGNE { get; set; } = new List<F_PROJETLIGNE>();

    public virtual ICollection<F_PROJETPLANNING> F_PROJETPLANNING { get; set; } = new List<F_PROJETPLANNING>();

    public virtual F_DEPOT cbDE_NoNavigation { get; set; }
}