// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class F_PROJETHISTO
{
    public string PF_Num { get; set; }

    public byte[] cbPF_Num { get; set; }

    public DateTime? PH_Date { get; set; }

    public int PP_No { get; set; }

    public decimal? PH_QteRealisee { get; set; }

    public string PH_TempsRealise { get; set; }

    public short? DO_Domaine { get; set; }

    public string DO_Piece { get; set; }

    public string PH_Intitule { get; set; }

    public short? PH_Type { get; set; }

    public string AR_RefCompose { get; set; }

    public byte[] cbAR_RefCompose { get; set; }

    public int? AG_No1Compose { get; set; }

    public int? AG_No2Compose { get; set; }

    public string PP_Operation { get; set; }

    public byte[] cbPP_Operation { get; set; }

    public string AR_RefComposant { get; set; }

    public byte[] cbAR_RefComposant { get; set; }

    public int? AG_No1Composant { get; set; }

    public int? AG_No2Composant { get; set; }

    public int? DE_No { get; set; }

    public int? cbDE_No { get; set; }

    public decimal? PH_QteReservee { get; set; }

    public short? PF_Type { get; set; }

    public decimal? PH_CoutRealise { get; set; }

    public short? cbProt { get; set; }

    public int cbMarq { get; set; }

    public string cbCreateur { get; set; }

    public DateTime? cbModification { get; set; }

    public int? cbReplication { get; set; }

    public short? cbFlag { get; set; }

    public virtual F_ARTICLE AR_RefComposantNavigation { get; set; }

    public virtual F_ARTICLE AR_RefComposeNavigation { get; set; }

    public virtual F_PROJETFABRICATION PF_NumNavigation { get; set; }

    public virtual F_PROJETPLANNING PP_NoNavigation { get; set; }
}