// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class F_RESSOURCEPROD
{
    public string RP_Code { get; set; }

    public byte[] cbRP_Code { get; set; }

    public short? RP_Type { get; set; }

    public string RP_Intitule { get; set; }

    public byte[] cbRP_Intitule { get; set; }

    public string RP_Complement { get; set; }

    public string RP_Central { get; set; }

    public byte[] cbRP_Central { get; set; }

    public DateTime? RP_Visite { get; set; }

    public decimal? RP_CoutStd { get; set; }

    public string RP_Temps { get; set; }

    public short? RP_Sommeil { get; set; }

    public int? RP_Capacite { get; set; }

    public string RP_Commentaire { get; set; }

    public short? RP_TypeRess { get; set; }

    public string RP_CodeExterne { get; set; }

    public int DE_No { get; set; }

    public string RP_Adresse { get; set; }

    public string RP_ComplementAdresse { get; set; }

    public string RP_CodePostal { get; set; }

    public string RP_Ville { get; set; }

    public string RP_Region { get; set; }

    public string RP_Pays { get; set; }

    public string RP_Telephone { get; set; }

    public string RP_Portable { get; set; }

    public string RP_EMail { get; set; }

    public string AR_RefDefaut { get; set; }

    public short? RP_Unite { get; set; }

    public short? RP_Continue { get; set; }

    public int? CAL_No { get; set; }

    public string RP_Horaire0101RP_PlageDebut { get; set; }

    public string RP_Horaire0101RP_PlageFin { get; set; }

    public string RP_Horaire0102RP_PlageDebut { get; set; }

    public string RP_Horaire0102RP_PlageFin { get; set; }

    public string RP_Horaire0201RP_PlageDebut { get; set; }

    public string RP_Horaire0201RP_PlageFin { get; set; }

    public string RP_Horaire0202RP_PlageDebut { get; set; }

    public string RP_Horaire0202RP_PlageFin { get; set; }

    public string RP_Horaire0301RP_PlageDebut { get; set; }

    public string RP_Horaire0301RP_PlageFin { get; set; }

    public string RP_Horaire0302RP_PlageDebut { get; set; }

    public string RP_Horaire0302RP_PlageFin { get; set; }

    public string RP_Horaire0401RP_PlageDebut { get; set; }

    public string RP_Horaire0401RP_PlageFin { get; set; }

    public string RP_Horaire0402RP_PlageDebut { get; set; }

    public string RP_Horaire0402RP_PlageFin { get; set; }

    public string RP_Horaire0501RP_PlageDebut { get; set; }

    public string RP_Horaire0501RP_PlageFin { get; set; }

    public string RP_Horaire0502RP_PlageDebut { get; set; }

    public string RP_Horaire0502RP_PlageFin { get; set; }

    public string RP_Horaire0601RP_PlageDebut { get; set; }

    public string RP_Horaire0601RP_PlageFin { get; set; }

    public string RP_Horaire0602RP_PlageDebut { get; set; }

    public string RP_Horaire0602RP_PlageFin { get; set; }

    public string RP_Horaire0701RP_PlageDebut { get; set; }

    public string RP_Horaire0701RP_PlageFin { get; set; }

    public string RP_Horaire0702RP_PlageDebut { get; set; }

    public string RP_Horaire0702RP_PlageFin { get; set; }

    public short? cbProt { get; set; }

    public int cbMarq { get; set; }

    public string cbCreateur { get; set; }

    public DateTime? cbModification { get; set; }

    public int? cbReplication { get; set; }

    public short? cbFlag { get; set; }

    public string RP_Facebook { get; set; }

    public string RP_LinkedIn { get; set; }

    public string RP_Skype { get; set; }

    public DateTime? cbCreation { get; set; }

    public Guid? cbCreationUser { get; set; }

    public virtual F_ARTICLE AR_RefDefautNavigation { get; set; }

    public virtual F_CALENDRIER CAL_NoNavigation { get; set; }

    public virtual F_DEPOT DE_NoNavigation { get; set; }

    public virtual ICollection<F_ABOLIGNE> F_ABOLIGNE { get; set; } = new List<F_ABOLIGNE>();

    public virtual ICollection<F_ARTCOMPO> F_ARTCOMPO { get; set; } = new List<F_ARTCOMPO>();

    public virtual ICollection<F_ARTICLE> F_ARTICLE { get; set; } = new List<F_ARTICLE>();

    public virtual ICollection<F_ARTICLERESSOURCE> F_ARTICLERESSOURCE { get; set; } = new List<F_ARTICLERESSOURCE>();

    public virtual ICollection<F_DOCLIGNE> F_DOCLIGNE { get; set; } = new List<F_DOCLIGNE>();

    public virtual ICollection<F_PROJETPLANNING> F_PROJETPLANNING { get; set; } = new List<F_PROJETPLANNING>();

    public virtual ICollection<F_RESSCENTRE> F_RESSCENTRERP_CodeCentreNavigation { get; set; } = new List<F_RESSCENTRE>();

    public virtual ICollection<F_RESSCENTRE> F_RESSCENTRERP_CodeRessourceNavigation { get; set; } = new List<F_RESSCENTRE>();
}