// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB
{
    public partial class F_REPCOM
    {
        public int CO_No { get; set; }
        public int TF_No { get; set; }
        public short? TF_Interes { get; set; }
        public short? cbProt { get; set; }
        public int cbMarq { get; set; }
        public string cbCreateur { get; set; }
        public DateTime? cbModification { get; set; }
        public int? cbReplication { get; set; }
        public short? cbFlag { get; set; }

        public virtual F_COLLABORATEUR CO_NoNavigation { get; set; }
        public virtual F_TARIF TF_NoNavigation { get; set; }
    }
}