// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class F_REGTAXE
{
    public int EC_No { get; set; }

    public int? RT_No { get; set; }

    public short? RT_Type { get; set; }

    public DateTime? RT_DateReg { get; set; }

    public DateTime? RT_DatePiece { get; set; }

    public string CT_Num { get; set; }

    public byte[] cbCT_Num { get; set; }

    public short? TA_Provenance01 { get; set; }

    public short? TA_Provenance02 { get; set; }

    public short? TA_Provenance03 { get; set; }

    public short? TA_Provenance04 { get; set; }

    public short? TA_Provenance05 { get; set; }

    public short? TA_Provenance06 { get; set; }

    public short? TA_Provenance07 { get; set; }

    public short? TA_Provenance08 { get; set; }

    public short? TA_Provenance09 { get; set; }

    public short? TA_Provenance10 { get; set; }

    public string CG_Num01 { get; set; }

    public string CG_Num02 { get; set; }

    public string CG_Num03 { get; set; }

    public string CG_Num04 { get; set; }

    public string CG_Num05 { get; set; }

    public string CG_Num06 { get; set; }

    public string CG_Num07 { get; set; }

    public string CG_Num08 { get; set; }

    public string CG_Num09 { get; set; }

    public string CG_Num10 { get; set; }

    public short? TA_TTaux01 { get; set; }

    public short? TA_TTaux02 { get; set; }

    public short? TA_TTaux03 { get; set; }

    public short? TA_TTaux04 { get; set; }

    public short? TA_TTaux05 { get; set; }

    public short? TA_TTaux06 { get; set; }

    public short? TA_TTaux07 { get; set; }

    public short? TA_TTaux08 { get; set; }

    public short? TA_TTaux09 { get; set; }

    public short? TA_TTaux10 { get; set; }

    public decimal? TA_Taux01 { get; set; }

    public decimal? TA_Taux02 { get; set; }

    public decimal? TA_Taux03 { get; set; }

    public decimal? TA_Taux04 { get; set; }

    public decimal? TA_Taux05 { get; set; }

    public decimal? TA_Taux06 { get; set; }

    public decimal? TA_Taux07 { get; set; }

    public decimal? TA_Taux08 { get; set; }

    public decimal? TA_Taux09 { get; set; }

    public decimal? TA_Taux10 { get; set; }

    public decimal? RT_Base01 { get; set; }

    public decimal? RT_Base02 { get; set; }

    public decimal? RT_Base03 { get; set; }

    public decimal? RT_Base04 { get; set; }

    public decimal? RT_Base05 { get; set; }

    public decimal? RT_Base06 { get; set; }

    public decimal? RT_Base07 { get; set; }

    public decimal? RT_Base08 { get; set; }

    public decimal? RT_Base09 { get; set; }

    public decimal? RT_Base10 { get; set; }

    public decimal? RT_Montant01 { get; set; }

    public decimal? RT_Montant02 { get; set; }

    public decimal? RT_Montant03 { get; set; }

    public decimal? RT_Montant04 { get; set; }

    public decimal? RT_Montant05 { get; set; }

    public decimal? RT_Montant06 { get; set; }

    public decimal? RT_Montant07 { get; set; }

    public decimal? RT_Montant08 { get; set; }

    public decimal? RT_Montant09 { get; set; }

    public decimal? RT_Montant10 { get; set; }

    public string TA_Code01 { get; set; }

    public string TA_Code02 { get; set; }

    public string TA_Code03 { get; set; }

    public string TA_Code04 { get; set; }

    public string TA_Code05 { get; set; }

    public string TA_Code06 { get; set; }

    public string TA_Code07 { get; set; }

    public string TA_Code08 { get; set; }

    public string TA_Code09 { get; set; }

    public string TA_Code10 { get; set; }

    public DateTime? JM_Date { get; set; }

    public string RT_NbFactures { get; set; }

    public short? RT_TypeTransac { get; set; }

    public string RT_NumeroDe { get; set; }

    public string RT_NumeroA { get; set; }

    public string RT_FactureRectif { get; set; }

    public string RT_Motif { get; set; }

    public short? cbProt { get; set; }

    public int cbMarq { get; set; }

    public string cbCreateur { get; set; }

    public DateTime? cbModification { get; set; }

    public int? cbReplication { get; set; }

    public short? cbFlag { get; set; }

    public byte[] cbHash { get; set; }

    public short? cbHashVersion { get; set; }

    public DateTime? cbHashDate { get; set; }

    public int? cbHashOrder { get; set; }

    public DateTime? cbCreation { get; set; }

    public Guid? cbCreationUser { get; set; }

    public short? RT_TypeLigne01 { get; set; }

    public short? RT_TypeLigne02 { get; set; }

    public short? RT_TypeLigne03 { get; set; }

    public short? RT_TypeLigne04 { get; set; }

    public short? RT_TypeLigne05 { get; set; }

    public short? RT_TypeLigne06 { get; set; }

    public short? RT_TypeLigne07 { get; set; }

    public short? RT_TypeLigne08 { get; set; }

    public short? RT_TypeLigne09 { get; set; }

    public short? RT_TypeLigne10 { get; set; }

    public virtual F_COMPTEG CG_Num01Navigation { get; set; }

    public virtual F_COMPTEG CG_Num02Navigation { get; set; }

    public virtual F_COMPTEG CG_Num03Navigation { get; set; }

    public virtual F_COMPTEG CG_Num04Navigation { get; set; }

    public virtual F_COMPTEG CG_Num05Navigation { get; set; }

    public virtual F_COMPTEG CG_Num06Navigation { get; set; }

    public virtual F_COMPTEG CG_Num07Navigation { get; set; }

    public virtual F_COMPTEG CG_Num08Navigation { get; set; }

    public virtual F_COMPTEG CG_Num09Navigation { get; set; }

    public virtual F_COMPTEG CG_Num10Navigation { get; set; }

    public virtual F_COMPTET CT_NumNavigation { get; set; }

    public virtual F_ECRITUREC EC_NoNavigation { get; set; }

    public virtual F_TAXE TA_Code01Navigation { get; set; }

    public virtual F_TAXE TA_Code02Navigation { get; set; }

    public virtual F_TAXE TA_Code03Navigation { get; set; }

    public virtual F_TAXE TA_Code04Navigation { get; set; }

    public virtual F_TAXE TA_Code05Navigation { get; set; }

    public virtual F_TAXE TA_Code06Navigation { get; set; }

    public virtual F_TAXE TA_Code07Navigation { get; set; }

    public virtual F_TAXE TA_Code08Navigation { get; set; }

    public virtual F_TAXE TA_Code09Navigation { get; set; }

    public virtual F_TAXE TA_Code10Navigation { get; set; }
}