// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB
{
    public partial class F_TARIFQTE
    {
        public string AR_Ref { get; set; }
        public byte[] cbAR_Ref { get; set; }
        public string TQ_RefCF { get; set; }
        public byte[] cbTQ_RefCF { get; set; }
        public decimal? TQ_BorneSup { get; set; }
        public decimal? TQ_Remise01REM_Valeur { get; set; }
        public short? TQ_Remise01REM_Type { get; set; }
        public decimal? TQ_Remise02REM_Valeur { get; set; }
        public short? TQ_Remise02REM_Type { get; set; }
        public decimal? TQ_Remise03REM_Valeur { get; set; }
        public short? TQ_Remise03REM_Type { get; set; }
        public decimal? TQ_PrixNet { get; set; }
        public short? cbProt { get; set; }
        public int cbMarq { get; set; }
        public string cbCreateur { get; set; }
        public DateTime? cbModification { get; set; }
        public int? cbReplication { get; set; }
        public short? cbFlag { get; set; }

        public virtual F_ARTICLE AR_RefNavigation { get; set; }
    }
}