// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class F_TICKETARCHIVE
{
    public int CA_No { get; set; }

    public int? CO_NoCaissier { get; set; }

    public int? cbCO_NoCaissier { get; set; }

    public string TA_Piece { get; set; }

    public byte[] cbTA_Piece { get; set; }

    public DateTime? TA_Date { get; set; }

    public string TA_Heure { get; set; }

    public string CT_Num { get; set; }

    public byte[] cbCT_Num { get; set; }

    public string DO_Piece { get; set; }

    public byte[] cbDO_Piece { get; set; }

    public short? cbProt { get; set; }

    public int cbMarq { get; set; }

    public string cbCreateur { get; set; }

    public DateTime? cbModification { get; set; }

    public int? cbReplication { get; set; }

    public short? cbFlag { get; set; }

    public DateTime? cbCreation { get; set; }

    public Guid? cbCreationUser { get; set; }

    public virtual F_CAISSE CA_NoNavigation { get; set; }

    public virtual ICollection<F_LIGNEARCHIVE> F_LIGNEARCHIVE { get; set; } = new List<F_LIGNEARCHIVE>();

    public virtual ICollection<F_REGLEARCHIVE> F_REGLEARCHIVE { get; set; } = new List<F_REGLEARCHIVE>();
}