// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB
{
    public partial class F_TICKETARCHIVE
    {
        public F_TICKETARCHIVE()
        {
            F_LIGNEARCHIVE = new HashSet<F_LIGNEARCHIVE>();
            F_REGLEARCHIVE = new HashSet<F_REGLEARCHIVE>();
        }

        public int CA_No { get; set; }
        public int? CO_NoCaissier { get; set; }
        public int? cbCO_NoCaissier { get; set; }
        public string TA_Piece { get; set; }
        public byte[] cbTA_Piece { get; set; }
        public DateTime? TA_Date { get; set; }
        public string TA_Heure { get; set; }
        public string CT_Num { get; set; }
        public byte[] cbCT_Num { get; set; }
        public string DO_Piece { get; set; }
        public byte[] cbDO_Piece { get; set; }
        public short? cbProt { get; set; }
        public int cbMarq { get; set; }
        public string cbCreateur { get; set; }
        public DateTime? cbModification { get; set; }
        public int? cbReplication { get; set; }
        public short? cbFlag { get; set; }

        public virtual F_CAISSE CA_NoNavigation { get; set; }
        public virtual F_COMPTET CT_NumNavigation { get; set; }
        public virtual F_COLLABORATEUR cbCO_NoCaissierNavigation { get; set; }
        public virtual ICollection<F_LIGNEARCHIVE> F_LIGNEARCHIVE { get; set; }
        public virtual ICollection<F_REGLEARCHIVE> F_REGLEARCHIVE { get; set; }
    }
}