// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB
{
    public partial class P_CATTARIF
    {
        public string CT_Intitule { get; set; }
        public short? CT_PrixTTC { get; set; }
        public short? cbIndice { get; set; }
        public int cbMarq { get; set; }
    }
}