// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB
{
    public partial class P_COLREGLEMENT
    {
        public short? CR_NumPiece01 { get; set; }
        public short? CR_NumPiece02 { get; set; }
        public string CR_Numero01 { get; set; }
        public string CR_Numero02 { get; set; }
        public short? CR_ColReglement01 { get; set; }
        public short? CR_ColReglement02 { get; set; }
        public short? CR_ColReglement03 { get; set; }
        public short? CR_ColReglement04 { get; set; }
        public short? CR_ColReglement05 { get; set; }
        public short? CR_ColReglement06 { get; set; }
        public short? CR_ColReglement07 { get; set; }
        public short? CR_ColReglement08 { get; set; }
        public short? CR_ColReglement09 { get; set; }
        public short? CR_ColReglement10 { get; set; }
        public short? CR_ColReglement11 { get; set; }
        public short? CR_ColReglement12 { get; set; }
        public short? CR_ColReglement13 { get; set; }
        public short? CR_ColReglement14 { get; set; }
        public short? CR_ColReglement15 { get; set; }
        public short? CR_ColReglement16 { get; set; }
        public short? CR_ColReglement17 { get; set; }
        public short? CR_ColReglement18 { get; set; }
        public short? CR_ColReglement19 { get; set; }
        public short? CR_ColReglement20 { get; set; }
        public short? CR_ColReglement21 { get; set; }
        public short? CR_ColReglement22 { get; set; }
        public short? CR_ColReglement23 { get; set; }
        public int cbMarq { get; set; }
    }
}