// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class P_COMPTOIR
{
    public string C_Intitule { get; set; }

    public short? C_Modele { get; set; }

    public short? C_Affiche01 { get; set; }

    public short? C_Affiche02 { get; set; }

    public short? C_Affiche03 { get; set; }

    public short? C_Affiche04 { get; set; }

    public short? C_Affiche05 { get; set; }

    public short? C_Affiche06 { get; set; }

    public short? C_Affiche07 { get; set; }

    public short? C_Affiche08 { get; set; }

    public short? C_Affiche09 { get; set; }

    public short? C_Affiche10 { get; set; }

    public short? C_Affiche11 { get; set; }

    public short? C_Affiche12 { get; set; }

    public short? C_Affiche13 { get; set; }

    public short? C_Affiche14 { get; set; }

    public short? C_Affiche15 { get; set; }

    public short? C_Affiche16 { get; set; }

    public short? C_Affiche17 { get; set; }

    public short? C_Affiche18 { get; set; }

    public short? C_Affiche19 { get; set; }

    public short? C_Affiche20 { get; set; }

    public short? C_Affiche21 { get; set; }

    public short? C_Affiche22 { get; set; }

    public short? C_Affiche23 { get; set; }

    public short? C_Affiche24 { get; set; }

    public short? C_Affiche25 { get; set; }

    public short? C_Affiche26 { get; set; }

    public short? C_Affiche27 { get; set; }

    public short? C_Affiche28 { get; set; }

    public short? C_Affiche29 { get; set; }

    public short? C_Affiche30 { get; set; }

    public short? C_Affiche31 { get; set; }

    public short? C_Affiche32 { get; set; }

    public short? C_Affiche33 { get; set; }

    public short? C_Affiche34 { get; set; }

    public short? C_Affiche35 { get; set; }

    public short? C_Affiche36 { get; set; }

    public short? C_Affiche37 { get; set; }

    public short? C_Colonne01 { get; set; }

    public short? C_Colonne02 { get; set; }

    public short? C_Colonne03 { get; set; }

    public short? C_Colonne04 { get; set; }

    public short? C_Colonne05 { get; set; }

    public short? C_Colonne06 { get; set; }

    public short? C_Colonne07 { get; set; }

    public short? C_Colonne08 { get; set; }

    public short? C_Colonne09 { get; set; }

    public short? C_Colonne10 { get; set; }

    public short? C_Colonne11 { get; set; }

    public short? C_Colonne12 { get; set; }

    public short? C_Colonne13 { get; set; }

    public short? C_Colonne14 { get; set; }

    public short? C_Colonne15 { get; set; }

    public short? C_Colonne16 { get; set; }

    public short? C_Colonne17 { get; set; }

    public short? C_Colonne18 { get; set; }

    public short? C_Colonne19 { get; set; }

    public short? C_Colonne20 { get; set; }

    public short? C_Colonne21 { get; set; }

    public short? C_Colonne22 { get; set; }

    public short? C_Colonne23 { get; set; }

    public short? C_Colonne24 { get; set; }

    public short? C_Colonne25 { get; set; }

    public short? C_Colonne26 { get; set; }

    public short? C_Colonne27 { get; set; }

    public short? C_Colonne28 { get; set; }

    public short? C_Colonne29 { get; set; }

    public short? C_Colonne30 { get; set; }

    public short? C_Colonne31 { get; set; }

    public short? C_Colonne32 { get; set; }

    public short? C_Colonne33 { get; set; }

    public short? C_Colonne34 { get; set; }

    public short? C_Colonne35 { get; set; }

    public short? C_Colonne36 { get; set; }

    public short? C_Colonne37 { get; set; }

    public short? C_Colonne38 { get; set; }

    public short? C_Colonne39 { get; set; }

    public short? C_Colonne40 { get; set; }

    public short? C_Colonne41 { get; set; }

    public short? C_Colonne42 { get; set; }

    public short? C_Colonne43 { get; set; }

    public short? C_Colonne44 { get; set; }

    public short? C_Colonne45 { get; set; }

    public short? C_Colonne46 { get; set; }

    public short? C_Colonne47 { get; set; }

    public short? C_Colonne48 { get; set; }

    public short? C_Colonne49 { get; set; }

    public short? C_Colonne50 { get; set; }

    public short? C_Colonne51 { get; set; }

    public short? C_Colonne52 { get; set; }

    public short? C_Colonne53 { get; set; }

    public short? C_Colonne54 { get; set; }

    public short? C_Colonne55 { get; set; }

    public short? C_Colonne56 { get; set; }

    public short? C_Colonne57 { get; set; }

    public short? C_Colonne58 { get; set; }

    public short? C_Colonne59 { get; set; }

    public short? C_Colonne60 { get; set; }

    public short? C_Colonne61 { get; set; }

    public short? C_Colonne62 { get; set; }

    public short? C_Colonne63 { get; set; }

    public short? C_Colonne64 { get; set; }

    public short? C_Colonne65 { get; set; }

    public short? C_Colonne66 { get; set; }

    public short? C_Colonne67 { get; set; }

    public short? C_Colonne68 { get; set; }

    public short? C_Colonne69 { get; set; }

    public short? C_Colonne70 { get; set; }

    public short? C_Colonne71 { get; set; }

    public short? C_Colonne72 { get; set; }

    public short? C_Colonne73 { get; set; }

    public short? C_Colonne74 { get; set; }

    public short? C_Colonne75 { get; set; }

    public short? C_Colonne76 { get; set; }

    public short? C_Colonne77 { get; set; }

    public short? C_Colonne78 { get; set; }

    public short? C_Colonne79 { get; set; }

    public short? C_Colonne80 { get; set; }

    public short? C_Colonne81 { get; set; }

    public short? C_Colonne82 { get; set; }

    public short? C_Colonne83 { get; set; }

    public short? C_Colonne84 { get; set; }

    public short? C_Colonne85 { get; set; }

    public short? C_Colonne86 { get; set; }

    public short? C_Colonne87 { get; set; }

    public short? C_Colonne88 { get; set; }

    public short? C_Colonne89 { get; set; }

    public short? C_Colonne90 { get; set; }

    public short? C_Colonne91 { get; set; }

    public short? C_Colonne92 { get; set; }

    public short? C_Colonne93 { get; set; }

    public short? C_TypeDoc { get; set; }

    public string C_BtnTexte01 { get; set; }

    public string C_BtnTexte02 { get; set; }

    public string C_BtnTexte03 { get; set; }

    public string C_BtnTexte04 { get; set; }

    public string C_BtnTexte05 { get; set; }

    public string C_BtnTexte06 { get; set; }

    public string C_BtnTexte07 { get; set; }

    public string C_BtnTexte08 { get; set; }

    public string C_BtnTexte09 { get; set; }

    public string C_BtnTexte10 { get; set; }

    public string C_BtnTexte11 { get; set; }

    public string C_BtnTexte12 { get; set; }

    public string C_BtnTexte13 { get; set; }

    public string C_BtnTexte14 { get; set; }

    public string C_BtnTexte15 { get; set; }

    public string C_BtnTexte16 { get; set; }

    public string C_BtnTexte17 { get; set; }

    public string C_BtnTexte18 { get; set; }

    public string C_BtnTexte19 { get; set; }

    public string C_BtnTexte20 { get; set; }

    public string C_BtnTexte21 { get; set; }

    public string C_BtnTexte22 { get; set; }

    public string C_BtnTexte23 { get; set; }

    public string C_BtnTexte24 { get; set; }

    public string C_BtnTexte25 { get; set; }

    public string C_BtnTexte26 { get; set; }

    public string C_BtnTexte27 { get; set; }

    public string C_BtnTexte28 { get; set; }

    public string C_BtnTexte29 { get; set; }

    public string C_BtnTexte30 { get; set; }

    public string C_BtnTexte31 { get; set; }

    public string C_BtnTexte32 { get; set; }

    public string C_BtnTexte33 { get; set; }

    public string C_BtnTexte34 { get; set; }

    public string C_BtnTexte35 { get; set; }

    public string C_BtnTexte36 { get; set; }

    public string C_BtnTexte37 { get; set; }

    public short? C_BtnFonction01 { get; set; }

    public short? C_BtnFonction02 { get; set; }

    public short? C_BtnFonction03 { get; set; }

    public short? C_BtnFonction04 { get; set; }

    public short? C_BtnFonction05 { get; set; }

    public short? C_BtnFonction06 { get; set; }

    public short? C_BtnFonction07 { get; set; }

    public short? C_BtnFonction08 { get; set; }

    public short? C_BtnFonction09 { get; set; }

    public short? C_BtnFonction10 { get; set; }

    public short? C_BtnFonction11 { get; set; }

    public short? C_BtnFonction12 { get; set; }

    public short? C_BtnFonction13 { get; set; }

    public short? C_BtnFonction14 { get; set; }

    public short? C_BtnFonction15 { get; set; }

    public short? C_BtnFonction16 { get; set; }

    public short? C_BtnFonction17 { get; set; }

    public short? C_BtnFonction18 { get; set; }

    public short? C_BtnFonction19 { get; set; }

    public short? C_BtnFonction20 { get; set; }

    public short? C_BtnFonction21 { get; set; }

    public short? C_BtnFonction22 { get; set; }

    public short? C_BtnFonction23 { get; set; }

    public short? C_BtnFonction24 { get; set; }

    public short? C_BtnFonction25 { get; set; }

    public short? C_BtnFonction26 { get; set; }

    public short? C_BtnFonction27 { get; set; }

    public short? C_BtnFonction28 { get; set; }

    public short? C_BtnFonction29 { get; set; }

    public short? C_BtnFonction30 { get; set; }

    public short? C_BtnFonction31 { get; set; }

    public short? C_BtnFonction32 { get; set; }

    public short? C_BtnFonction33 { get; set; }

    public short? C_BtnFonction34 { get; set; }

    public short? C_BtnFonction35 { get; set; }

    public short? C_BtnFonction36 { get; set; }

    public short? C_BtnFonction37 { get; set; }

    public short? cbIndice { get; set; }

    public int cbMarq { get; set; }
}