// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB
{
    public partial class P_EXPEDITION
    {
        public string E_Intitule { get; set; }
        public string E_Mode { get; set; }
        public string AR_Ref { get; set; }
        public short? E_TypeFrais { get; set; }
        public decimal? E_ValFrais { get; set; }
        public short? E_TypeLigneFrais { get; set; }
        public short? E_TypeFranco { get; set; }
        public decimal? E_ValFranco { get; set; }
        public short? E_TypeLigneFranco { get; set; }
        public short? cbIndice { get; set; }
        public int cbMarq { get; set; }
    }
}