// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB
{
    public partial class P_GENAUTO
    {
        public short? GE_ArtNumerot { get; set; }
        public short? GE_ArtLen { get; set; }
        public short? GE_ArtTypeRacine { get; set; }
        public string GE_ArtRacine { get; set; }
        public short? GE_GamNumerot { get; set; }
        public short? GE_GamIncrement { get; set; }
        public short? GE_GamLen { get; set; }
        public short? GE_GamTypeRacine { get; set; }
        public short? GE_GamLenRacine { get; set; }
        public string GE_GamRacine { get; set; }
        public short? GE_GamTypeComplt { get; set; }
        public short? GE_GamLenComplt { get; set; }
        public short? GE_CondiNumerot { get; set; }
        public short? GE_CondiIncrement { get; set; }
        public short? GE_CondiLen { get; set; }
        public short? GE_CondiTypeRacine { get; set; }
        public short? GE_CondiLenRacine { get; set; }
        public string GE_CondiRacine { get; set; }
        public short? GE_CondiTypeComplt { get; set; }
        public short? GE_CondiLenComplt { get; set; }
        public short? GE_CBArtNumerot { get; set; }
        public short? GE_CBArtNorme { get; set; }
        public short? GE_CBArtLen { get; set; }
        public short? GE_CBArtTypeRacine { get; set; }
        public short? GE_CBArtLenRacine { get; set; }
        public string GE_CBArtRacine { get; set; }
        public short? GE_CBGamNumerot { get; set; }
        public short? GE_CBGamIncrement { get; set; }
        public short? GE_CBGamNorme { get; set; }
        public short? GE_CBGamLen { get; set; }
        public short? GE_CBGamTypeRacine { get; set; }
        public short? GE_CBGamLenRacine { get; set; }
        public string GE_CBGamRacine { get; set; }
        public short? GE_CBGamTypeComplt { get; set; }
        public short? GE_CBGamLenComplt { get; set; }
        public short? GE_CBCondiNumerot { get; set; }
        public short? GE_CBCondiIncrement { get; set; }
        public short? GE_CBCondiNorme { get; set; }
        public short? GE_CBCondiLen { get; set; }
        public short? GE_CBCondiTypeRacine { get; set; }
        public short? GE_CBCondiLenRacine { get; set; }
        public string GE_CBCondiRacine { get; set; }
        public short? GE_CBCondiTypeComplt { get; set; }
        public short? GE_CBCondiLenComplt { get; set; }
        public int cbMarq { get; set; }
    }
}