// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class P_INTSTATART
{
    public string P_IntStatArt1 { get; set; }

    public short? cbIndice { get; set; }

    public int cbMarq { get; set; }
}