// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessWeb.Models.DB;

public partial class P_SECURITYSTRATEGYCPTA
{
    public short? SECUR_PwdRenouv { get; set; }

    public short? SECUR_PwdComplex { get; set; }

    public short? SECUR_PwdChain { get; set; }

    public short? SECUR_PwdRequired { get; set; }

    public int cbMarq { get; set; }

    public short? SECUR_PwdStrong { get; set; }
}